import { useState } from 'react';
import { Dialog, Field, PageHeading } from '../components/UI.jsx';
import { EntryForm, Report, downloadCSV } from '../components/OperationsUI.jsx';
import { dateKey } from '../app/model.js';
const marks={work:'Явка',off:'Выходной',leave:'Отпуск',sick:'Больничный'};
const codes={off:'В',leave:'ОТ',sick:'Б'};
export function Attendance({state,command,search}) {
  const [month,setMonth]=useState(dateKey().slice(0,7)); const [modal,setModal]=useState(null); const [report,setReport]=useState(null);
  const year=Number(month.slice(0,4)), monthIndex=Number(month.slice(5))-1;
  const days=Array.from({length:new Date(year,monthIndex+1,0).getDate()},(_,i)=>`${month}-${String(i+1).padStart(2,'0')}`);
  const people=state.employees.filter((p)=>(p.active||state.attendance.some((a)=>a.employeeId===p.id&&a.date.startsWith(month)))&&`${p.name} ${p.department}`.toLowerCase().includes(search.toLowerCase()));
  const entries=new Map(state.attendance.filter((a)=>a.date.startsWith(month)).map((a)=>[`${a.employeeId}:${a.date}`,a]));
  const totals=(person)=>{const rows=days.map((date)=>entries.get(`${person.id}:${date}`)).filter(Boolean);return {days:rows.filter((a)=>a.kind==='work'&&a.hours>0).length,hours:Math.round(rows.reduce((n,a)=>n+a.hours,0)*100)/100};};
  const printable={title:`Табель рабочего времени · ${month}`,subtitle:'Я — явка (часы); В — выходной; ОТ — отпуск; Б — больничный. Пустая ячейка — нет отметки.',headers:['Сотрудник',...days.map((_,i)=>String(i+1)),'Дней','Часов'],rows:people.map((p)=>[p.name,...days.map((date)=>{const a=entries.get(`${p.id}:${date}`);return a?(a.kind==='work'?a.hours:codes[a.kind]):'';}),totals(p).days,totals(p).hours])};
  return <section className="page"><PageHeading title="Табель сотрудников" description="Фактически отработанные дни и часы"/><div className="toolbar"><input aria-label="Месяц табеля" type="month" value={month} onChange={(e)=>e.target.value&&setMonth(e.target.value)}/><button className="button primary" onClick={()=>setModal({date:dateKey(),employeeId:people[0]?.id,kind:'work',hours:8})}>Добавить отметку</button><button className="button" onClick={()=>setReport(printable)}>Печать / PDF</button><button className="button" onClick={()=>downloadCSV(printable.title,printable.headers,printable.rows)}>Выгрузить CSV</button></div><p className="ops-hint">Нажмите на день, чтобы внести или изменить часы. Один день может содержать до 24 часов. План задач не заполняет фактический табель автоматически.</p><div className="table-wrap attendance-wrap"><table className="attendance-table"><thead><tr><th>Сотрудник</th>{days.map((date,i)=><th key={date}>{i+1}</th>)}<th>Дней</th><th>Часов</th></tr></thead><tbody>{people.map((p)=><tr key={p.id}><th>{p.name}<small>{p.department}</small></th>{days.map((date)=>{const a=entries.get(`${p.id}:${date}`);return <td key={date} className={[0,6].includes(new Date(date+'T12:00').getDay())?'weekend':''}><button aria-label={`${p.name}, ${date}`} onClick={()=>setModal(a||{employeeId:p.id,date,kind:'work',hours:8})}>{a?(a.kind==='work'?a.hours:codes[a.kind]):'·'}</button></td>;})}<td><strong>{totals(p).days}</strong></td><td><strong>{totals(p).hours}</strong></td></tr>)}</tbody></table></div><p className="ops-hint">В — выходной · ОТ — отпуск · Б — больничный. Не является расчётом заработной платы.</p>{modal?<Dialog title="Отметка табеля" onClose={()=>setModal(null)}><AttendanceForm state={state} entry={modal} onClose={()=>setModal(null)} onSubmit={(p)=>{command('attendance.save',p);setModal(null);}}/></Dialog>:null}{report?<Report report={report} onClose={()=>setReport(null)}/>:null}</section>;
}
function AttendanceForm({state,entry,onClose,onSubmit}) {
  const [kind,setKind]=useState(entry.kind);
  return <EntryForm onClose={onClose} onSubmit={(p)=>onSubmit({...p,kind})}><Field label="Сотрудник" wide><select name="employeeId" required defaultValue={entry.employeeId||''}><option value="">Выберите сотрудника</option>{state.employees.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Дата"><input name="date" type="date" required defaultValue={entry.date}/></Field><Field label="Отметка"><select value={kind} onChange={(e)=>setKind(e.target.value)}>{Object.entries(marks).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field>{kind==='work'?<Field label="Отработано часов"><input name="hours" type="number" min="0.01" max="24" step="0.01" required defaultValue={entry.hours||8}/></Field>:null}<Field label="Примечание" wide><textarea name="note" defaultValue={entry.note}/></Field></EntryForm>;
}

