import { useEffect, useState } from 'react';
import { Banknote, CalendarCheck, Clock3, LockKeyhole, LogOut, Printer, Settings2 } from 'lucide-react';
import { Avatar, Dialog, Field, PageHeading } from '../components/UI.jsx';
import { EntryForm, Report, downloadCSV } from '../components/OperationsUI.jsx';
import { dateKey } from '../app/model.js';
import { money, round } from '../app/operations.js';

const marks={work:'Явка',off:'Выходной',leave:'Отпуск',sick:'Больничный'};
const codes={off:'В',leave:'ОТ',sick:'Б'};
const quickMarks=[
  {id:'8',label:'+ 8 ч',kind:'work',hours:8},
  {id:'4',label:'4 ч',kind:'work',hours:4},
  {id:'6',label:'6 ч',kind:'work',hours:6},
  {id:'10',label:'10 ч',kind:'work',hours:10},
  {id:'off',label:'Выходной',kind:'off',hours:0},
  {id:'leave',label:'Отпуск',kind:'leave',hours:0},
  {id:'sick',label:'Больничный',kind:'sick',hours:0},
  {id:'detail',label:'Подробно'},
];
const ACCESS_KEY='eft-crm.attendance.finances-unlocked';
const formatDate=(value)=>value.toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric'});

function AccessGate({onUnlock}) {
  const [pin,setPin]=useState(''); const [error,setError]=useState('');
  function submit(event){event.preventDefault();if(pin.replace(/\s/g,'')==='911'){sessionStorage.setItem(ACCESS_KEY,'1');onUnlock();}else{setError('Неверный пароль');setPin('');}}
  return <div className="attendance-lock finance-lock"><span><LockKeyhole size={28}/></span><h2>Финансовая часть закрыта</h2><p>Введите пароль, чтобы увидеть ставки, начисления и финансовую ведомость.</p><form onSubmit={submit}><label><span>Пароль</span><input type="password" inputMode="numeric" autoComplete="off" autoFocus value={pin} onChange={(event)=>setPin(event.target.value)} aria-label="Пароль финансовой части табеля" placeholder="Введите пароль"/></label><button className="button primary">Открыть финансы</button></form>{error?<p className="form-error" role="alert">{error}</p>:null}<small>Рабочие часы доступны без пароля. Финансовый доступ сохраняется до закрытия вкладки.</small></div>;
}

export function Attendance({state,command,search,runtime={mode:'demo'},notify=()=>{}}) {
  const serverMode=runtime.mode==='server'; const canFinance=!serverMode||runtime.capabilities?.includes('*')||runtime.capabilities?.includes('finance.view');
  const [financesUnlocked,setFinancesUnlocked]=useState(()=>serverMode?canFinance:sessionStorage.getItem(ACCESS_KEY)==='1');
  const [month,setMonth]=useState(dateKey().slice(0,7)); const [modal,setModal]=useState(null); const [report,setReport]=useState(null); const [rates,setRates]=useState(false); const [quickMark,setQuickMark]=useState('8');
  const [loading,setLoading]=useState(serverMode);
  useEffect(()=>{if(!serverMode)return;let active=true;setLoading(true);runtime.loadAttendance(month).catch((error)=>notify(error.message,true)).finally(()=>active&&setLoading(false));return()=>{active=false;};},[month,serverMode]);
  const year=Number(month.slice(0,4)), monthIndex=Number(month.slice(5))-1;
  const days=Array.from({length:new Date(year,monthIndex+1,0).getDate()},(_,i)=>`${month}-${String(i+1).padStart(2,'0')}`);
  const people=state.employees.filter((p)=>(p.active||state.attendance.some((a)=>a.employeeId===p.id&&a.date.startsWith(month)))&&`${p.name} ${p.department}`.toLowerCase().includes(search.toLowerCase()));
  const entries=new Map(state.attendance.filter((a)=>a.date.startsWith(month)).map((a)=>[`${a.employeeId}:${a.date}`,a]));
  const totals=(person,lastDay=days.length)=>{const rows=days.slice(0,lastDay).map((date)=>entries.get(`${person.id}:${date}`)).filter(Boolean);const work=rows.filter((a)=>a.kind==='work'&&a.hours>0);const result={days:work.length,hours:round(work.reduce((n,a)=>n+(person.attendanceMode==='days'?0:a.hours),0))};return {...result,pay:round((person.attendanceMode==='days'?result.days:result.hours)*person.payRate)};};
  const advanceFor=(person)=>person.advanceAmount>0?person.advanceAmount:round(totals(person,25).pay*.3);
  const summary=people.reduce((result,person)=>{const row=totals(person);result.days+=row.days;result.hours+=row.hours;result.pay+=row.pay;result.advance+=advanceFor(person);return result;},{days:0,hours:0,pay:0,advance:0});
  const markText=(person,entry)=>entry?(entry.kind==='work'?(person.attendanceMode==='days'||entry.hours===8?'+':entry.hours):codes[entry.kind]):'·';
  const printable={title:`Табель рабочего времени · ${month}`,subtitle:'+ — 8 рабочих часов или явка без учёта часов; В — выходной; ОТ — отпуск; Б — больничный.',headers:['Сотрудник',...days.map((_,i)=>String(i+1)),'Дней','Часов'],rows:people.map((p)=>[p.name,...days.map((date)=>markText(p,entries.get(`${p.id}:${date}`))==='·'?'':markText(p,entries.get(`${p.id}:${date}`))),totals(p).days,p.attendanceMode==='days'?'—':totals(p).hours])};
  const ratesReport={title:`Ведомость ставок и начислений · ${month}`,subtitle:'Предварительный расчёт по данным табеля. Ставка применяется за час или за отмеченный рабочий день.',headers:['Сотрудник','Способ учёта','Ставка','Дней','Часов','Начислено'],rows:people.map((p)=>[p.name,p.attendanceMode==='days'?'По дням':'По часам',`${p.payRate.toLocaleString('ru-RU')} ₽ / ${p.attendanceMode==='days'?'день':'час'}`,totals(p).days,p.attendanceMode==='days'?'—':totals(p).hours,money(totals(p).pay)]),footer:`Всего предварительно начислено: ${money(summary.pay)}`};
  const advanceDate=formatDate(new Date(year,monthIndex,25)); const settlementDate=formatDate(new Date(year,monthIndex+1,10));
  const salaryReport={title:`Зарплатная ведомость · ${month}`,subtitle:`Аванс — ${advanceDate}; окончательный расчёт за месяц — ${settlementDate}. Если фиксированный аванс не задан, используется 30% начисления по табелю с 1 по 25 число.`,headers:['Сотрудник','Начислено','Аванс к 25 числу','Основание аванса','К выплате 10 числа'],rows:people.map((p)=>{const pay=totals(p).pay;const advance=advanceFor(p);return [p.name,money(pay),money(advance),p.advanceAmount>0?'Фиксированная сумма':'30% заработанного по 25 число',money(pay-advance)];}),footer:`Итого начислено: ${money(summary.pay)} · аванс: ${money(summary.advance)} · окончательный расчёт: ${money(summary.pay-summary.advance)}`};
  function lockFinances(){sessionStorage.removeItem(ACCESS_KEY);setFinancesUnlocked(false);setRates(false);}
  async function saveMark(payload){if(serverMode)await runtime.saveAttendance(payload);else command('attendance.save',payload);notify('Отметка табеля сохранена');}
  function markCell(person,date,entry){const quick=quickMarks.find((item)=>item.id===quickMark);if(!quick||quick.id==='detail'){setModal(entry||{employeeId:person.id,date,kind:'work',hours:person.attendanceMode==='days'?1:8});return;}saveMark({employeeId:person.id,date,kind:quick.kind,hours:person.attendanceMode==='days'&&quick.kind==='work'?1:quick.hours,note:entry?.note||''}).catch((error)=>notify(error.message,true));}
  return <section className="page attendance-page"><PageHeading title="Табель сотрудников" description="Рабочие дни и часы сотрудников">{financesUnlocked&&!serverMode?<button className="button" onClick={lockFinances}><LogOut size={16}/>Закрыть финансы</button>:null}</PageHeading>
    <div className={`attendance-summary ${financesUnlocked?'':'finances-locked'}`}><article><CalendarCheck size={22}/><span>Рабочих дней<strong>{summary.days}</strong></span></article><article><Clock3 size={22}/><span>Учтено часов<strong>{summary.hours}</strong></span></article>{financesUnlocked?<><article className="pay-card"><Banknote size={22}/><span>Начислено<strong>{money(summary.pay)}</strong></span></article><button onClick={()=>setRates(true)}><Settings2 size={21}/><span>Ставки и авансы<small>Настроить расчёт</small></span></button></>:<button className="finance-access" onClick={()=>!serverMode&&setModal({type:'finance-access'})}><LockKeyhole size={21}/><span>Финансовая часть<small>{serverMode?'Нет финансовых прав':'Ставки и начисления закрыты'}</small></span></button>}</div>
    <div className="toolbar"><input aria-label="Месяц табеля" type="month" value={month} onChange={(e)=>e.target.value&&setMonth(e.target.value)}/><button className="button primary" disabled={!people.length||loading} onClick={()=>setModal({date:dateKey(),employeeId:people[0]?.id,kind:'work',hours:8})}>{loading?'Загрузка…':'Добавить отметку'}</button><button className="button" onClick={()=>setReport(printable)}><Printer size={16}/>Печать табеля</button>{financesUnlocked?<><button className="button" onClick={()=>setReport(ratesReport)}><Banknote size={16}/>Печать ставок</button><button className="button" onClick={()=>setReport(salaryReport)}><Printer size={16}/>Зарплатная ведомость</button></>:null}<button className="button" onClick={()=>downloadCSV(printable.title,printable.headers,printable.rows)}>Выгрузить CSV</button></div>
    <div className="attendance-quick" aria-label="Быстрая отметка"><span>Быстрое заполнение:</span>{quickMarks.map((item)=><button key={item.id} className={`${quickMark===item.id?'active':''} mark-${item.kind||'detail'}`} aria-pressed={quickMark===item.id} onClick={()=>setQuickMark(item.id)}>{item.label}</button>)}<small>Выберите отметку, затем нажимайте нужные дни в таблице.</small></div>
    <p className="ops-hint">Восемь рабочих часов отображаются знаком «+», другое количество — числом. Для произвольных часов и примечания выберите «Подробно».</p>
    <div className="table-wrap attendance-wrap"><table className="attendance-table"><thead><tr><th>Сотрудник</th>{days.map((date,i)=><th key={date}>{i+1}</th>)}<th>Дней</th><th>Часов</th></tr></thead><tbody>{people.map((p)=><tr key={p.id}><th><span className="attendance-person"><Avatar id={p.id} state={state}/><span>{p.name}<small>{p.department}{financesUnlocked?` · ${p.payRate.toLocaleString('ru-RU')} ₽/${p.attendanceMode==='days'?'день':'час'}`:''}</small></span></span></th>{days.map((date)=>{const a=entries.get(`${p.id}:${date}`);const weekend=[0,6].includes(new Date(date+'T12:00').getDay());return <td key={date} className={`${weekend?'weekend ':''}${a?`mark-${a.kind}`:''}`}><button aria-label={`${p.name}, ${date}, ${a?markText(p,a):'нет отметки'}`} title={a?marks[a.kind]:'Нет отметки'} onClick={()=>markCell(p,date,a)}>{markText(p,a)}</button></td>;})}<td><strong>{totals(p).days}</strong></td><td><strong>{p.attendanceMode==='days'?'—':totals(p).hours}</strong></td></tr>)}</tbody></table></div>
    <p className="ops-hint">Рабочий табель доступен сотрудникам. Ставки, авансы, суммы начислений и зарплатная ведомость открываются только по паролю.</p>
    {modal?.type==='finance-access'&&!serverMode?<Dialog title="Доступ к финансовой части" onClose={()=>setModal(null)}><AccessGate onUnlock={()=>{setFinancesUnlocked(true);setModal(null);}}/></Dialog>:null}
    {modal&&!modal.type?<Dialog title="Отметка табеля" onClose={()=>setModal(null)}><AttendanceForm state={state} entry={modal} onClose={()=>setModal(null)} onSubmit={async(payload)=>{await saveMark(payload);setModal(null);}}/></Dialog>:null}
    {rates?<Dialog title="Ставки и авансы сотрудников" subtitle="Ставка за час или день; нулевой фиксированный аванс означает расчёт 30%" onClose={()=>setRates(false)} wide><RatesForm state={state} onClose={()=>setRates(false)} onSubmit={async(rows)=>{if(serverMode)await runtime.saveRates(rows);else command('employee.rates.save',{rows});notify('Ставки и авансы сохранены');setRates(false);}}/></Dialog>:null}
    {report?<Report report={report} onClose={()=>setReport(null)}/>:null}
  </section>;
}

function AttendanceForm({state,entry,onClose,onSubmit}) {
  const [kind,setKind]=useState(entry.kind); const [employeeId,setEmployeeId]=useState(entry.employeeId||''); const person=state.employees.find((item)=>item.id===employeeId); const byDays=person?.attendanceMode==='days';
  return <EntryForm onClose={onClose} onSubmit={(payload)=>onSubmit({...payload,kind,employeeId,hours:byDays?1:payload.hours})}><Field label="Сотрудник" wide><select required value={employeeId} onChange={(event)=>setEmployeeId(event.target.value)}><option value="">Выберите сотрудника</option>{state.employees.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Дата"><input name="date" type="date" required defaultValue={entry.date}/></Field><Field label="Отметка"><select value={kind} onChange={(event)=>setKind(event.target.value)}>{Object.entries(marks).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field>{kind==='work'&&!byDays?<Field label="Отработано часов"><input name="hours" type="number" min="0.01" max="24" step="0.01" required defaultValue={entry.hours||8}/></Field>:null}{kind==='work'&&byDays?<p className="form-hint">Для этого сотрудника будет поставлен знак «+» без ввода часов.</p>:null}<Field label="Примечание" wide><textarea name="note" defaultValue={entry.note}/></Field></EntryForm>;
}

function RatesForm({state,onClose,onSubmit}) {
  const [rows,setRows]=useState(()=>state.employees.map((person)=>({id:person.id,attendanceMode:person.attendanceMode,payRate:person.payRate,advanceAmount:person.advanceAmount||0})));
  const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  function update(id,patch){setRows((current)=>current.map((row)=>row.id===id?{...row,...patch}:row));}
  return <form onSubmit={async(event)=>{event.preventDefault();setBusy(true);setError('');try{await onSubmit(rows);}catch(nextError){setError(nextError.message);setBusy(false);}}}><div className="form-content rate-editor"><div className="rate-head"><span>Сотрудник</span><span>Учёт</span><span>Ставка, ₽</span><span>Фикс. аванс, ₽</span></div>{state.employees.map((person)=>{const row=rows.find((item)=>item.id===person.id);return <div className="rate-row" key={person.id}><span className="attendance-person"><Avatar id={person.id} state={state}/><span><strong>{person.name}</strong><small>{person.role}</small></span></span><select aria-label={`Учёт ${person.name}`} value={row.attendanceMode} onChange={(event)=>update(person.id,{attendanceMode:event.target.value})}><option value="hours">По часам</option><option value="days">По дням (+)</option></select><input aria-label={`Ставка ${person.name}`} type="number" min="0" max="10000000" step="0.01" value={row.payRate} onChange={(event)=>update(person.id,{payRate:event.target.value})}/><input aria-label={`Фиксированный аванс ${person.name}`} title="0 — рассчитывать 30%" type="number" min="0" max="10000000" step="0.01" value={row.advanceAmount} onChange={(event)=>update(person.id,{advanceAmount:event.target.value})}/></div>;})}<p className="form-hint">Если фиксированный аванс равен 0, ведомость рассчитает 30% заработанного по табелю с 1 по 25 число.</p>{error?<p className="form-error" role="alert">{error}</p>:null}</div><footer className="dialog-actions"><button type="button" className="button" onClick={onClose} disabled={busy}>Отмена</button><button className="button primary" disabled={busy}>{busy?'Сохраняем…':'Сохранить ставки и авансы'}</button></footer></form>;
}
