import { useState } from 'react';
import { PageHeading } from '../components/UI.jsx';
import { dateKey, employee, leadContext, taskContext } from '../app/model.js';
export function Calendar({state,search,onLead,onTask}) {
  const [view,setView]=useState('month'); const [anchor,setAnchor]=useState(dateKey()); const [owner,setOwner]=useState('');
  const current=new Date(anchor+'T12:00'), year=current.getFullYear(), month=current.getMonth();
  const events=[...state.leads.filter((l)=>l.dueAt&&l.status!=='lost').map((l)=>({id:l.id,kind:'lead',title:l.nextAction,date:l.dueAt,owner:l.ownerId,label:leadContext(state,l).client.name})),...state.tasks.filter((t)=>t.dueAt&&t.status!=='done').map((t)=>({id:t.id,kind:'task',title:t.title,date:t.dueAt,owner:t.assigneeId,label:taskContext(state,t).order?.number||'Общая задача'}))].filter((e)=>(!owner||e.owner===owner)&&`${e.title} ${e.label}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>a.date.localeCompare(b.date));
  const byDay=new Map();for(const event of events){const key=event.date.slice(0,10);if(!byDay.has(key))byDay.set(key,[]);byDay.get(key).push(event);}
  function shift(direction){const d=new Date(current);if(view==='year')d.setFullYear(year+direction);else if(view==='month'){d.setDate(1);d.setMonth(month+direction);}else d.setDate(d.getDate()+direction*7);setAnchor(dateKey(d));}
  const start=view==='week'?new Date(current):new Date(year,month,1,12);start.setDate(start.getDate()-(start.getDay()+6)%7);
  const days=Array.from({length:view==='week'?7:42},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return d;});
  return <section className="page"><PageHeading title="Календарь" description="Сроки контактов и задач сотрудников"/><div className="toolbar"><div className="segmented">{[['week','Неделя'],['month','Месяц'],['year','Год']].map(([key,label])=><button key={key} className={view===key?'active':''} onClick={()=>setView(key)}>{label}</button>)}</div><button className="button" aria-label="Предыдущий период" onClick={()=>shift(-1)}>←</button><button className="button" onClick={()=>setAnchor(dateKey())}>Сегодня</button><button className="button" aria-label="Следующий период" onClick={()=>shift(1)}>→</button><input aria-label="Дата календаря" type="date" value={anchor} onChange={(e)=>e.target.value&&setAnchor(e.target.value)}/><select aria-label="Сотрудник в календаре" value={owner} onChange={(e)=>setOwner(e.target.value)}><option value="">Все сотрудники</option>{state.employees.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><h2 className="calendar-period">{view==='year'?year:current.toLocaleDateString('ru-RU',{month:'long',year:'numeric'})}</h2>
    {view==='year'?<div className="year-grid">{Array.from({length:12},(_,m)=>{const first=new Date(year,m,1,12),blank=(first.getDay()+6)%7,count=new Date(year,m+1,0).getDate();return <section className="mini-month" key={m}><button className="month-title" onClick={()=>{setAnchor(dateKey(first));setView('month');}}>{first.toLocaleDateString('ru-RU',{month:'long'})}</button><div className="mini-days">{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map((d)=><span key={d}>{d}</span>)}{Array.from({length:blank},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:count},(_,i)=>{const key=dateKey(new Date(year,m,i+1,12)),list=byDay.get(key)||[];return <button key={key} className={list.length?'has-events':''} title={`${key}: ${list.length} событий`} onClick={()=>{setAnchor(key);setView('week');}}>{i+1}{list.length?<i/>:null}</button>;})}</div></section>;})}</div>:<div className={`calendar-expanded ${view}`}>{days.map((d)=>{const key=dateKey(d),list=byDay.get(key)||[];return <section key={key} className={`calendar-cell ${key===dateKey()?'today':''} ${d.getMonth()!==month?'outside':''}`}><header><span>{d.toLocaleDateString('ru-RU',{weekday:'short'})}</span><strong>{d.getDate()}</strong></header>{list.map((e)=><button className={`calendar-event ${e.kind}`} key={e.kind+e.id} onClick={()=>e.kind==='lead'?onLead(e.id):onTask(e.id)}><span>{e.date.slice(11,16)} · {employee(e.owner,state)?.name||'Не назначен'}</span><strong>{e.title}</strong><small>{e.label}</small></button>)}</section>;})}</div>}
  </section>;
}
