import { useEffect, useMemo, useRef, useState } from 'react';
import { AlertCircle, ArrowUpRight, Check, CheckCheck, Download, FileText, Inbox, Mail, MessageSquare, Paperclip, Phone, Plus, RefreshCw, Reply, Search, Send, Settings2, X } from 'lucide-react';
import { Empty, PageHeading, VoiceInput } from '../components/UI.jsx';
import { dateLabel, employee } from '../app/model.js';

const CHANNELS = [
  { id: '', label: 'Все каналы', icon: MessageSquare }, { id: 'email', label: 'Почта', icon: Mail },
  { id: 'whatsapp', label: 'WhatsApp', icon: MessageSquare }, { id: 'telegram', label: 'Telegram', icon: Send },
  { id: 'max', label: 'MAX', icon: MessageSquare }, { id: 'note', label: 'Внутренние', icon: Phone },
];
const QUICK_REPLIES = ['Спасибо, получили информацию.', 'Подготовим расчёт и вернёмся с ответом.', 'Уточните, пожалуйста, удобное время для звонка.'];
const STATUS = { internal: ['В CRM', Check], saved: ['Сохранено', Check], queued: ['В очереди', Check], sent: ['Отправлено', CheckCheck], delivered: ['Доставлено', CheckCheck], error: ['Ошибка', AlertCircle] };
const channelName = (id) => CHANNELS.find((item) => item.id === id)?.label || (id === 'call' ? 'Звонок' : 'Система');
const filesOf = (item) => (item.attachments || []).filter((file) => file?.key || file?.name);
const UNASSIGNED = '__unassigned_email__';
const senderOf = (item) => item.attachments?.find((entry) => entry?.kind === 'sender')?.email || '';

export function Communications({ state, search, command, runtime = { mode: 'demo' }, notify, onCreate, onLead }) {
  const [channel, setChannel] = useState(''); const [sendChannel, setSendChannel] = useState('email'); const [selectedSite, setSelectedSite] = useState('');
  const [onlyUnread, setOnlyUnread] = useState(false); const [message, setMessage] = useState(''); const [subject, setSubject] = useState('');
  const [settingsOpen, setSettingsOpen] = useState(false); const [connectors, setConnectors] = useState([]); const [files, setFiles] = useState([]); const [replyTo, setReplyTo] = useState(null); const [busy, setBusy] = useState(false); const [syncing, setSyncing] = useState(false); const [assignments, setAssignments] = useState({});
  const fileInput = useRef(null);
  useEffect(() => { if (!runtime.loadConnectorStatuses) return; const controller = new AbortController(); runtime.loadConnectorStatuses(controller.signal).then(setConnectors).catch(() => setConnectors([])); return () => controller.abort(); }, [runtime.loadConnectorStatuses]);
  const conversations = useMemo(() => {
    const available = state.activities.filter((item) => item.channel !== 'system' && (!channel || item.channel === channel) && (!onlyUnread || !item.read));
    return state.sites.map((site) => { const client = state.clients.find((item) => item.id === site.clientId); const items = available.filter((item) => item.siteId === site.id).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)); const all = state.activities.filter((item)=>item.siteId===site.id&&(!channel||item.channel===channel)); return {site,client,last:items[0],unread:all.filter((item)=>!item.read).length}; })
      .filter((row)=>`${row.client?.name} ${row.site.name} ${row.last?.text||''}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>new Date(b.last?.createdAt||0)-new Date(a.last?.createdAt||0));
  }, [channel, onlyUnread, search, state.activities, state.clients, state.sites]);
  const unassigned = useMemo(() => state.activities.filter((item) => item.channel === 'email' && item.direction === 'incoming' && !item.siteId && (!onlyUnread || !item.read)).sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)), [onlyUnread, state.activities]);
  const activeId = selectedSite === UNASSIGNED && (!channel || channel === 'email') ? UNASSIGNED : selectedSite && state.sites.some((site)=>site.id===selectedSite) ? selectedSite : conversations[0]?.site.id || '';
  const inboxSelected = activeId === UNASSIGNED; const active = state.sites.find((item)=>item.id===activeId); const client = state.clients.find((item)=>item.id===active?.clientId); const lead = state.leads.find((item)=>item.siteId===activeId);
  const thread = useMemo(()=>state.activities.filter((item)=>inboxSelected ? item.channel==='email'&&item.direction==='incoming'&&!item.siteId : item.siteId===activeId&&(!channel||item.channel===channel)&&item.channel!=='system').sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt)),[activeId,channel,inboxSelected,state.activities]);
  const activeConnector = connectors.find((item)=>item.id===sendChannel); const unreadTotal=state.activities.filter((item)=>!item.read).length;
  async function send(event) {
    event.preventDefault(); if (busy) return; setBusy(true);
    try {
      if (runtime.sendCommunication) {
        const result = await runtime.sendCommunication({siteId:activeId,channel:sendChannel,subject,text:message,replyTo:replyTo?.id||'',files});
        if (result.deliveryStatus==='error') notify(`Сообщение сохранено, но не отправлено: ${result.deliveryError}`,true); else notify(result.deliveryStatus==='sent'?'Сообщение отправлено':'Сообщение сохранено в CRM');
      } else command('communication.send',{siteId:activeId,channel:sendChannel,subject,text:message,attachments:files.map((file)=>({name:file.name,size:file.size,mime:file.type}))});
      setMessage(''); setSubject(''); setFiles([]); setReplyTo(null);
    } catch(error) { notify(error.message,true); } finally { setBusy(false); }
  }
  function addFiles(event) { const next=[...files,...event.target.files]; const total=next.reduce((sum,file)=>sum+file.size,0); if(next.length>8||next.some((file)=>file.size>10*1024*1024)||total>25*1024*1024){notify('До 8 файлов: каждый до 10 МБ, всего до 25 МБ.',true);return;} setFiles(next); event.target.value=''; }
  async function selectConversation(id){setSelectedSite(id);try{await command('communication.read',{siteId:id,channel});}catch(error){notify(error.message,true);}}
  async function syncInbox() { if (syncing) return; setSyncing(true); try { const result = await runtime.syncMail(); notify(`Почта проверена: новых писем ${result.summary.imported}, без клиента ${result.summary.unassigned}.`); } catch (error) { notify(error.message, true); } finally { setSyncing(false); } }
  async function assignMessage(id) { const siteId = assignments[id]; if (!siteId) return; try { await runtime.assignCommunication(id, siteId); setAssignments((current) => { const next = { ...current }; delete next[id]; return next; }); setSelectedSite(siteId); notify('Письмо привязано к клиенту'); } catch (error) { notify(error.message, true); } }
  return <section className="page communications-page">
    <PageHeading title="Центр общения" description="Письма, мессенджеры, звонки и история клиента в одном окне"><div className="communication-heading-actions">{runtime.syncMail?<button className="button" onClick={syncInbox} disabled={syncing}><RefreshCw size={17}/>{syncing?'Проверяем…':'Проверить почту'}</button>:null}<button className="button" onClick={()=>setSettingsOpen((value)=>!value)}><Settings2 size={17}/>Подключения</button><button className="button primary" onClick={()=>onCreate(activeId)} disabled={!activeId||inboxSelected}><Plus size={18}/>Записать звонок</button></div></PageHeading>
    {settingsOpen?<section className="connector-panel"><div><strong>Каналы связи</strong><span>Ключи хранятся только на сервере CRM</span></div>{(connectors.length?connectors:[{id:'email',name:'Почта'},{id:'telegram',name:'Telegram'},{id:'whatsapp',name:'WhatsApp'},{id:'max',name:'MAX'}]).map((item)=><article key={item.id}><span className={`connector-mark ${item.status||'pending'}`}/><div><strong>{item.name}</strong><small>{item.detail||'Ожидает настройки'}</small></div></article>)}</section>:null}
    <div className="communication-workspace">
      <aside className="channel-rail"><strong>Каналы</strong>{CHANNELS.map(({id,label,icon:Icon})=>{const count=state.activities.filter((item)=>(!id||item.channel===id)&&!item.read).length;return <button key={id||'all'} className={channel===id?'active':''} onClick={()=>{setChannel(id);setSelectedSite('');}}><Icon size={17}/><span>{label}</span>{count?<b>{count}</b>:null}</button>;})}<button className={`unread-filter ${onlyUnread?'active':''}`} onClick={()=>setOnlyUnread((value)=>!value)}><CheckCheck size={17}/><span>Непрочитанные</span>{unreadTotal?<b>{unreadTotal}</b>:null}</button></aside>
      <section className="conversation-column"><div className="conversation-search"><Search size={16}/><span>{onlyUnread?'Непрочитанные диалоги':'Последние диалоги'}</span></div>{(!channel||channel==='email')&&unassigned.length?<button className={`conversation-card ${inboxSelected?'active':''}`} onClick={()=>setSelectedSite(UNASSIGNED)}><span className="conversation-avatar"><Inbox size={19}/></span><span className="conversation-copy"><strong>Неразобранные письма</strong><small>Отправитель ещё не привязан к клиенту</small><span>{senderOf(unassigned[0])||unassigned[0].subject||'Новое письмо'}</span></span><span className="conversation-meta"><b>{unassigned.length}</b></span></button>:null}{conversations.map((row)=><button key={row.site.id} className={`conversation-card ${activeId===row.site.id?'active':''}`} onClick={()=>selectConversation(row.site.id)}><span className="conversation-avatar">{row.client?.name?.split(' ').map((part)=>part[0]).slice(0,2).join('')}</span><span className="conversation-copy"><strong>{row.client?.name}</strong><small>{row.site.name}{row.last?` · ${channelName(row.last.channel)}`:''}</small><span>{row.last?.text||'Начать общение'}</span></span><span className="conversation-meta">{row.last?<time>{dateLabel(row.last.createdAt)}</time>:null}{row.unread?<b>{row.unread}</b>:null}</span></button>)}{!conversations.length&&!unassigned.length?<Empty title="Диалогов нет">Измените фильтр или запишите общение.</Empty>:null}</section>
      <section className="thread-column">{active||inboxSelected?<><header className="thread-header"><div><strong>{inboxSelected?'Неразобранные письма':client?.name}</strong><span>{inboxSelected?'Выберите клиента для каждого письма':`${active.name} · ${client?.phone||'телефон не указан'} · ${client?.email||'почта не указана'}`}</span></div>{lead?<button className="text-link" onClick={()=>onLead(lead.id)}>Карточка клиента<ArrowUpRight size={14}/></button>:null}</header>
        <div className="message-thread">{thread.map((item)=>{const status=STATUS[item.deliveryStatus]||STATUS.saved;const StatusIcon=status[1];return <article key={item.id} className={`message-bubble ${item.direction}`}><header><small>{channelName(item.channel)}{item.subject?` · ${item.subject}`:''}</small>{!inboxSelected?<button type="button" title="Ответить" onClick={()=>{setReplyTo(item);setSendChannel(['note','call'].includes(item.channel)?'email':item.channel);}}><Reply size={13}/></button>:null}</header>{senderOf(item)?<small className="message-sender">От: {senderOf(item)}</small>:null}<p>{item.text}</p>{filesOf(item).length?<div className="message-files">{filesOf(item).map((file,index)=><a key={file.key||`${file.name}-${index}`} href={file.url||'#'} download={file.name}><FileText size={14}/><span>{file.name}</span><Download size={12}/></a>)}</div>:null}{inboxSelected?<div className="mail-assignment"><select aria-label="Клиент для письма" value={assignments[item.id]||''} onChange={(event)=>setAssignments((current)=>({...current,[item.id]:event.target.value}))}><option value="">Выберите клиента и объект</option>{state.sites.map((site)=><option key={site.id} value={site.id}>{state.clients.find((row)=>row.id===site.clientId)?.name||'Клиент'} · {site.name}</option>)}</select><button className="button" disabled={!assignments[item.id]} onClick={()=>assignMessage(item.id)}>Привязать</button></div>:null}<footer><span>{item.direction==='incoming'?(senderOf(item)||client?.name||'Клиент'):(employee(item.authorId,state)?.name||'ЭФТ')}</span><span className={`delivery-status ${item.deliveryStatus==='error'?'error':''}`} title={item.deliveryError||status[0]}><StatusIcon size={12}/>{status[0]}</span><time>{dateLabel(item.createdAt)}</time></footer></article>})}{!thread.length?<Empty title="В этом канале сообщений нет">Напишите первое сообщение ниже.</Empty>:null}</div>
        {inboxSelected?<div className="message-composer inbox-hint">Привяжите письмо к клиенту, чтобы отвечать из его карточки.</div>:<form className="message-composer" onSubmit={send}>{replyTo?<div className="reply-preview"><Reply size={14}/><span><strong>Ответ на сообщение</strong>{replyTo.text}</span><button type="button" onClick={()=>setReplyTo(null)}><X size={14}/></button></div>:null}{sendChannel==='email'?<input value={subject} onChange={(event)=>setSubject(event.target.value)} placeholder="Тема письма" maxLength={500}/>:null}{files.length?<div className="composer-files">{files.map((file,index)=><span key={`${file.name}-${file.lastModified}`}><Paperclip size={12}/>{file.name}<button type="button" onClick={()=>setFiles((current)=>current.filter((_,i)=>i!==index))}><X size={12}/></button></span>)}</div>:null}<div className="quick-replies">{QUICK_REPLIES.map((text)=><button type="button" key={text} onClick={()=>setMessage(text)}>{text}</button>)}</div><div className="composer-row"><select aria-label="Канал отправки" value={sendChannel} onChange={(event)=>setSendChannel(event.target.value)}><option value="email">Почта</option><option value="telegram">Telegram</option><option value="whatsapp">WhatsApp</option><option value="max">MAX</option><option value="note">Внутренняя заметка</option><option value="call">Итог звонка</option></select><VoiceInput><textarea aria-label="Новое сообщение" value={message} onChange={(event)=>setMessage(event.target.value)} placeholder="Введите сообщение или нажмите микрофон…" rows={2} maxLength={20000} required/></VoiceInput><input ref={fileInput} hidden type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf,text/plain,.zip,.docx,.xlsx" onChange={addFiles}/><button type="button" className="button attach-button" title="Прикрепить файлы" onClick={()=>fileInput.current?.click()}><Paperclip size={18}/></button><button className="button primary" aria-label="Отправить" disabled={busy}><Send size={18}/></button></div><small>{['note','call'].includes(sendChannel)?'Запись останется внутри CRM.':activeConnector?.status==='active'?'Канал подключён: сообщение будет отправлено адресату.':'Канал ожидает подключения: сообщение надёжно сохранится в CRM.'}</small></form>}</>:<Empty title="Выберите диалог"/>}</section>
    </div>
  </section>;
}
