import { useMemo, useState } from 'react';
import { AlertTriangle, ArrowLeft, ArrowRight, CalendarDays, Camera, CheckCircle2, CircleDot, Clock3, HardHat, MessageSquare, Pencil, Plus, UserRound } from 'lucide-react';
import { Badge, Empty, Field, PageHeading, VoiceInput } from '../components/UI.jsx';
import { CONSTRUCTION_STATUSES, CONSTRUCTION_TEMPLATES, SITE_STATUSES, dateLabel, employee } from '../app/model.js';
import './construction.css';

const day = (value) => value ? new Date(`${value}T12:00:00`).toLocaleDateString('ru-RU', { day: '2-digit', month: 'short', year: 'numeric' }) : 'Не указан';
const averageProgress = (stages) => stages.length ? Math.round(stages.reduce((sum, stage) => sum + stage.progress, 0) / stages.length) : 0;

function SiteForm({ site, state, onCancel, onSave }) {
  const [form, setForm] = useState(site); const change = (key) => (event) => setForm((value) => ({ ...value, [key]: event.target.value }));
  return <form onSubmit={(event) => { event.preventDefault(); onSave(form); }}><div className="form-content form-grid">
    <Field label="Статус"><select value={form.status} onChange={change('status')}>{SITE_STATUSES.map((status) => <option key={status.id} value={status.id}>{status.label}</option>)}</select></Field>
    <Field label="Ответственный"><select value={form.managerId} onChange={change('managerId')}><option value="">Не назначен</option>{state.employees.filter((person) => person.active).map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></Field>
    <Field label="Номер договора"><input value={form.contractNumber} onChange={change('contractNumber')} /></Field>
    <Field label="План: начало"><input type="date" value={form.plannedStart} onChange={change('plannedStart')} /></Field>
    <Field label="План: завершение"><input type="date" value={form.plannedFinish} onChange={change('plannedFinish')} /></Field>
    <Field label="Факт: начало"><input type="date" value={form.actualStart} onChange={change('actualStart')} /></Field>
    <Field label="Примечание" wide><textarea rows="4" value={form.notes} onChange={change('notes')} placeholder="Особенности объекта, ограничения, важные договорённости" /></Field>
  </div><footer className="dialog-actions"><button type="button" className="button" onClick={onCancel}>Отмена</button><button className="button primary">Сохранить объект</button></footer></form>;
}

function StageForm({ stage, siteId, state, siteStages, onCancel, onSave }) {
  const empty = { siteId, title: '', group: 'Монтаж', status: 'planned', progress: 0, plannedStart: '', plannedFinish: '', actualStart: '', actualFinish: '', assigneeId: '', crewId: '', dependencyIds: [], notes: '', blockReason: '' };
  const [form, setForm] = useState(stage || empty); const change = (key) => (event) => setForm((value) => ({ ...value, [key]: event.target.value }));
  return <form onSubmit={(event) => { event.preventDefault(); onSave(form); }}><div className="form-content form-grid">
    <Field label="Название этапа" wide><input required value={form.title} onChange={change('title')} list="construction-titles" /><datalist id="construction-titles">{CONSTRUCTION_TEMPLATES.map((item) => <option key={item.id} value={item.title} />)}</datalist></Field>
    <Field label="Раздел"><input required value={form.group} onChange={change('group')} /></Field>
    <Field label="Статус"><select value={form.status} onChange={change('status')}>{CONSTRUCTION_STATUSES.map((status) => <option key={status.id} value={status.id}>{status.label}</option>)}</select></Field>
    <Field label="Готовность, %"><input type="number" min="0" max="100" value={form.progress} onChange={change('progress')} /></Field>
    <Field label="Ответственный"><select value={form.assigneeId} onChange={change('assigneeId')}><option value="">Не назначен</option>{state.employees.filter((person) => person.active).map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></Field>
    <Field label="Бригада"><select value={form.crewId} onChange={change('crewId')}><option value="">Не назначена</option>{state.crews.filter((crew) => crew.active).map((crew) => <option key={crew.id} value={crew.id}>{crew.name}</option>)}</select></Field>
    <Field label="План: начало"><input type="date" value={form.plannedStart} onChange={change('plannedStart')} /></Field>
    <Field label="План: завершение"><input type="date" value={form.plannedFinish} onChange={change('plannedFinish')} /></Field>
    <Field label="Факт: начало"><input type="date" value={form.actualStart} onChange={change('actualStart')} /></Field>
    <Field label="Факт: завершение"><input type="date" value={form.actualFinish} onChange={change('actualFinish')} /></Field>
    <Field label="Зависит от" wide><select multiple value={form.dependencyIds} onChange={(event) => setForm((value) => ({ ...value, dependencyIds: [...event.target.selectedOptions].map((option) => option.value) }))}>{siteStages.filter((item) => item.id !== stage?.id).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><small className="form-hint">Для нескольких этапов удерживайте Ctrl.</small></Field>
    {form.status === 'blocked' ? <Field label="Причина задержки" wide><textarea required rows="2" value={form.blockReason} onChange={change('blockReason')} /></Field> : null}
    <Field label="Комментарий к этапу" wide><textarea rows="4" value={form.notes} onChange={change('notes')} /></Field>
  </div><footer className="dialog-actions"><button type="button" className="button" onClick={onCancel}>Отмена</button><button className="button primary">Сохранить этап</button></footer></form>;
}

function StageCard({ stage, index, state, siteStages, command, onEdit, uploadPhoto, onCreateTask }) {
  const [comment, setComment] = useState(''); const [uploading, setUploading] = useState(false); const dependencyNames = stage.dependencyIds.map((id) => siteStages.find((item) => item.id === id)?.title).filter(Boolean);
  const overdue = stage.status !== 'done' && stage.plannedFinish && new Date(`${stage.plannedFinish}T23:59:59`) < new Date();
  return <article className={`construction-stage ${stage.status}${overdue ? ' overdue' : ''}`}>
    <div className="stage-index">{stage.status === 'done' ? <CheckCircle2 size={20} /> : index + 1}</div>
    <div className="stage-main"><div className="stage-title"><div><small>{stage.group}</small><h3>{stage.title}</h3></div><Badge value={stage.status} stages={CONSTRUCTION_STATUSES} /></div>
      <div className="stage-progress"><progress value={stage.progress} max="100" /><strong>{stage.progress}%</strong></div>
      <div className="stage-facts"><span><CalendarDays size={15} />{day(stage.plannedStart)} — {day(stage.plannedFinish)}</span><span><UserRound size={15} />{employee(stage.assigneeId, state)?.name || state.crews.find((crew) => crew.id === stage.crewId)?.name || 'Не назначен'}</span>{overdue ? <span className="stage-warning"><AlertTriangle size={15} />Просрочен</span> : null}</div>
      {dependencyNames.length ? <p className="stage-dependencies">После: {dependencyNames.join(', ')}</p> : null}{stage.blockReason ? <p className="stage-block"><AlertTriangle size={15} />{stage.blockReason}</p> : null}{stage.notes ? <p className="stage-notes">{stage.notes}</p> : null}
      {stage.attachments.length ? <div className="stage-photos">{stage.attachments.map((photo) => <a href={`/uploads/construction/${encodeURIComponent(photo.key)}`} target="_blank" rel="noreferrer" key={photo.key}><img src={`/uploads/construction/${encodeURIComponent(photo.key)}`} alt={photo.name || 'Фото этапа'} /><span>{photo.name || 'Фото'}</span></a>)}</div> : null}
      <div className="stage-actions"><select aria-label="Статус этапа" value={stage.status} onChange={(event) => command('construction.stage.save', { id: stage.id, status: event.target.value }, 'Статус этапа обновлён')}>{CONSTRUCTION_STATUSES.map((status) => <option key={status.id} value={status.id}>{status.label}</option>)}</select><button className="button" onClick={() => onCreateTask(stage)}><Plus size={15} />Задача</button><button className="button" onClick={() => onEdit(stage)}><Pencil size={15} />Изменить</button>{uploadPhoto ? <label className="button file-button"><Camera size={15} />{uploading ? 'Загрузка…' : 'Добавить фото'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); try { await uploadPhoto(stage.id, file); } finally { setUploading(false); event.target.value = ''; } }} /></label> : null}</div>
      <details className="stage-comments"><summary><MessageSquare size={15} />Комментарии · {stage.comments.length}</summary>{stage.comments.map((item) => <div key={item.id}><strong>{employee(item.authorId, state)?.name || 'ЭФТ'}</strong><span>{dateLabel(item.createdAt)}</span><p>{item.text}</p></div>)}<form onSubmit={(event) => { event.preventDefault(); command('construction.stage.comment', { id: stage.id, text: comment }, 'Комментарий добавлен'); setComment(''); }}><VoiceInput><input value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Добавить комментарий голосом или текстом" required /></VoiceInput><button className="button" type="submit">Добавить</button></form></details>
    </div>
  </article>;
}

export function Construction({ state, search, selectedSiteId, onSelectSite, command, uploadPhoto, onCreateTask }) {
  const [editing, setEditing] = useState(null); const [editingSite, setEditingSite] = useState(false); const [startDate, setStartDate] = useState(new Date().toISOString().slice(0, 10));
  const siteRows = useMemo(() => state.sites.map((site) => { const stages = state.constructionStages.filter((stage) => stage.siteId === site.id); return { site, stages, progress: averageProgress(stages), client: state.clients.find((client) => client.id === site.clientId) }; }).filter((row) => `${row.site.name} ${row.site.address} ${row.client?.name}`.toLowerCase().includes(search.toLowerCase())), [state.sites, state.constructionStages, state.clients, search]);
  const row = siteRows.find((item) => item.site.id === selectedSiteId) || (!selectedSiteId ? null : { site: state.sites.find((site) => site.id === selectedSiteId), stages: state.constructionStages.filter((stage) => stage.siteId === selectedSiteId) });
  if (!row?.site) return <section className="page construction-page"><PageHeading title="Строительство" description="Объекты, этапы, сроки и текущая готовность" /><div className="construction-grid">{siteRows.map(({ site, stages, progress, client }) => { const current = stages.find((stage) => ['doing','blocked','review'].includes(stage.status)) || stages.find((stage) => stage.status !== 'done'); return <button className="construction-object" key={site.id} onClick={() => onSelectSite(site.id)}><div className="construction-object-head"><span><HardHat size={20} /></span><Badge value={site.status} stages={SITE_STATUSES} /></div><h2>{site.name}</h2><p>{client?.name || 'Клиент не указан'} · {site.address || 'Адрес не указан'}</p><div className="object-progress"><span><strong>{progress}%</strong> готово</span><progress value={progress} max="100" /></div><div className="object-current"><small>Текущий этап</small><strong>{current?.title || (stages.length ? 'Все этапы завершены' : 'План ещё не создан')}</strong></div><footer><span>{stages.filter((stage) => stage.status === 'done').length} из {stages.length} этапов</span><ArrowRight size={18} /></footer></button>; })}</div>{!siteRows.length ? <Empty title="Объекты не найдены" /> : null}</section>;

  const stages = row.stages; const progress = averageProgress(stages); const client = state.clients.find((item) => item.id === row.site.clientId);
  return <section className="page construction-page"><button className="back-link" onClick={() => onSelectSite('')}><ArrowLeft size={17} />Все объекты</button><div className="construction-header"><div><span className="construction-kicker">{client?.name} · {row.site.address}</span><h1>{row.site.name}</h1><div><Badge value={row.site.status} stages={SITE_STATUSES} /><span>Договор: {row.site.contractNumber || 'не указан'}</span><span>Ответственный: {employee(row.site.managerId, state)?.name || 'не назначен'}</span></div></div><button className="button" onClick={() => setEditingSite(true)}><Pencil size={16} />Параметры объекта</button></div>
    <div className="construction-summary"><div className="construction-ring" style={{ '--progress': `${progress * 3.6}deg` }}><span>{progress}%</span></div><div><small>Общая готовность</small><strong>{stages.filter((stage) => stage.status === 'done').length} из {stages.length} этапов завершено</strong></div><div><CalendarDays size={19} /><span><small>Плановый период</small><strong>{day(row.site.plannedStart)} — {day(row.site.plannedFinish)}</strong></span></div><div><Clock3 size={19} /><span><small>Требуют внимания</small><strong>{stages.filter((stage) => stage.status === 'blocked' || (stage.status !== 'done' && stage.plannedFinish && new Date(`${stage.plannedFinish}T23:59:59`) < new Date())).length}</strong></span></div></div>
    {!stages.length ? <div className="construction-empty"><CircleDot size={34} /><h2>План строительства ещё не создан</h2><p>Разверните типовой план из 18 связанных этапов. Даты рассчитаются автоматически и их можно будет изменить.</p><label>Начало работ<input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} /></label><button className="button primary" onClick={() => command('construction.plan.initialize', { siteId: row.site.id, startDate }, 'Типовой план строительства создан')}>Создать типовой план</button></div> : <><div className="construction-toolbar"><div><h2>Этапы строительства</h2><p>План, факт, зависимости, ответственные и фотографии</p></div><button className="button primary" onClick={() => setEditing({ siteId: row.site.id })}><Plus size={17} />Добавить этап</button></div><div className="construction-timeline">{stages.map((stage, index) => <StageCard key={stage.id} stage={stage} index={index} state={state} siteStages={stages} command={command} onEdit={setEditing} uploadPhoto={uploadPhoto} onCreateTask={onCreateTask} />)}</div></>}
    {editingSite ? <div className="construction-editor"><div className="construction-editor-card"><header><h2>Параметры объекта</h2><button className="icon-button" onClick={() => setEditingSite(false)}>×</button></header><SiteForm site={row.site} state={state} onCancel={() => setEditingSite(false)} onSave={(payload) => { command('construction.site.update', payload, 'Объект обновлён'); setEditingSite(false); }} /></div></div> : null}
    {editing ? <div className="construction-editor"><div className="construction-editor-card wide"><header><h2>{editing.id ? 'Изменить этап' : 'Новый этап'}</h2><button className="icon-button" onClick={() => setEditing(null)}>×</button></header><StageForm stage={editing.id ? editing : null} siteId={row.site.id} state={state} siteStages={stages} onCancel={() => setEditing(null)} onSave={(payload) => { command('construction.stage.save', payload, 'Этап сохранён'); setEditing(null); }} /></div></div> : null}
  </section>;
}
