import { useState } from 'react';
import { Plus, Printer } from 'lucide-react';
import { Dialog, Field, PageHeading, Empty } from '../components/UI.jsx';
import { EntryForm, Report, SectionTabs, downloadCSV } from '../components/OperationsUI.jsx';
import { dateKey } from '../app/model.js';
import { documentTypes, money, stockFor, receivedQuantity, PRICE_SOURCE, exportCalculatorPrices } from '../app/operations.js';

const tabs = [['stock','Склад'],['catalog','Общий прайс'],['purchases','Закупки'],['documents','Движения'],['tools','Инструмент'],['suppliers','Поставщики']];
export function Inventory({ state, command, search }) {
  const [tab, setTab] = useState('stock'); const [modal, setModal] = useState(null); const [report, setReport] = useState(null); const [query,setQuery] = useState(''); const [category,setCategory] = useState(''); const [page,setPage] = useState(0); const [notice,setNotice] = useState('');
  const close = () => setModal(null);
  function commit(action,payload) { command(action,payload); close(); setNotice('Документ сохранён'); }
  const stocks = new Map(state.materials.map((m) => [m.id,stockFor(state,m.id)]));
  const materials = state.materials.filter((m) => (tab !== 'stock' || m.tracked) && (!category || m.category === category) && `${m.id} ${m.name} ${m.category}`.toLowerCase().includes(`${search} ${query}`.trim().toLowerCase()));
  const totalValue = [...stocks.values()].reduce((n,s) => n+s.value,0);
  const filteredDocs = [...state.stockDocuments].reverse().filter((d) => `${d.number} ${d.target} ${d.reference} ${d.lines.map((l)=>l.name).join(' ')}`.toLowerCase().includes(search.toLowerCase()));
  function exportPrice(){const url=URL.createObjectURL(new Blob([JSON.stringify(exportCalculatorPrices(state),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='Прайс-лист_ЭФТ_CRM_v10.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const stockReport = () => ({ title: tab === 'stock' ? 'Ведомость складских остатков' : 'Прайс-лист материалов', subtitle: `На ${dateKey()} · ${PRICE_SOURCE}`, headers:['Код','Материал','Ед.','Остаток','Текущая цена','Стоимость остатка'], rows:materials.map((m)=>[m.id,m.name,m.unit,stocks.get(m.id).quantity,money(m.price),money(stocks.get(m.id).value)]) });
  function docReport(doc) { return { title:`${documentTypes[doc.kind] || 'Заказ поставщику'} ${doc.number}`, subtitle:`${doc.date} · ${doc.target || state.suppliers.find((s)=>s.id===doc.supplierId)?.name || ''} · ${doc.reference || ''}`, headers:['Материал','Ед.','Количество','Цена','Сумма'], rows:doc.lines.map((l)=>[l.name,l.unit,l.quantity,money(l.price),money(l.quantity*l.price)]), footer:`Итого: ${money(doc.lines.reduce((n,l)=>n+l.quantity*l.price,0))}. ${doc.note || ''}` }; }
  return <section className="page"><PageHeading title="Закупки и склад" description="Материалы, поступления, расход и инструмент" /><div className="ops-metrics"><div><strong>{state.materials.filter((m)=>m.tracked).length}</strong><span>позиций на складском учёте</span></div><div><strong>{money(totalValue)}</strong><span>стоимость остатка</span></div><div><strong>{state.materials.filter((m)=>m.tracked && stocks.get(m.id).quantity<m.minStock).length}</strong><span>ниже минимального запаса</span></div></div><SectionTabs items={tabs} value={tab} onChange={(value)=>{setTab(value);setPage(0);setQuery('');setCategory('');setNotice('');}} />{notice ? <p className="inline-notice" role="status">{notice}</p>:null}
    {['stock','catalog'].includes(tab) ? <><div className="toolbar"><input aria-label="Найти материал" placeholder="Название, категория, код" value={query} onChange={(e)=>{setQuery(e.target.value);setPage(0);}} /><select aria-label="Категория материалов" value={category} onChange={(e)=>{setCategory(e.target.value);setPage(0);}}><option value="">Все категории</option>{[...new Set(state.materials.map((m)=>m.category))].map((c)=><option key={c}>{c}</option>)}</select><button className="button" onClick={()=>setModal({type:'material'})}><Plus size={16}/>Материал</button><button className="button" onClick={()=>setReport(stockReport())}><Printer size={16}/>Печать</button>{tab==='catalog'?<button className="button" onClick={exportPrice}>Экспорт для калькулятора</button>:null}{tab==='stock'?<><button className="button primary" onClick={()=>setModal({type:'movement',kind:'receipt'})}>Приход</button><button className="button" onClick={()=>setModal({type:'movement',kind:'issue'})}>Расход</button></>:null}</div><p className="ops-hint">{tab==='stock'?'Остатки формируются из проведённых движений. Отметьте нужные позиции в общем прайсе для складского учёта.':'Исходный прайс из калькулятора. Цена обновляется при поступлении; ранее проведённые документы сохраняют свои суммы. Автоматический обмен с калькулятором ещё не подключён.'}</p><div className="table-wrap"><table><thead><tr><th>Материал</th><th>Ед.</th><th>Цена</th><th>Остаток</th><th>Мин. запас</th><th>Учёт</th><th>Действия</th></tr></thead><tbody>{materials.slice(page*40,page*40+40).map((m)=><tr key={m.id}><td><strong>{m.name}</strong><small>{m.id} · {m.category}{m.priceNote ? ` · ${m.priceNote}` : ''}</small></td><td>{m.unit}</td><td>{money(m.price)}</td><td className={stocks.get(m.id).quantity<m.minStock?'amber-text':''}>{m.tracked?stocks.get(m.id).quantity:'—'}</td><td>{m.minStock}</td><td>{m.tracked?'Склад':'Под заказ'}</td><td><button className="text-link" onClick={()=>setModal({type:'material',item:m})}>Изменить</button></td></tr>)}</tbody></table>{!materials.length?<Empty title="Материалов пока нет">Откройте общий прайс и включите складской учёт нужных позиций.</Empty>:null}</div><div className="toolbar pagination"><button className="button" disabled={page===0} onClick={()=>setPage(page-1)}>Назад</button><span>{page+1} / {Math.max(1,Math.ceil(materials.length/40))} · {materials.length} позиций</span><button className="button" disabled={(page+1)*40>=materials.length} onClick={()=>setPage(page+1)}>Далее</button></div></>:null}
    {tab==='suppliers'?<><div className="toolbar"><button className="button primary" onClick={()=>setModal({type:'supplier'})}>Добавить поставщика</button></div><div className="table-wrap"><table><thead><tr><th>Поставщик</th><th>Контакты</th><th>Примечание</th><th/></tr></thead><tbody>{state.suppliers.map((s)=><tr key={s.id}><td>{s.name}</td><td>{s.contact}</td><td>{s.notes}</td><td><button className="text-link" onClick={()=>setModal({type:'supplier',item:s})}>Изменить</button></td></tr>)}</tbody></table>{!state.suppliers.length?<Empty title="Добавьте поставщиков материалов"/>:null}</div></>:null}
    {tab==='purchases'?<><div className="toolbar"><button className="button primary" onClick={()=>setModal({type:'purchase'})}>Новая закупка</button></div><div className="table-wrap"><table><thead><tr><th>Документ</th><th>Поставщик</th><th>Срок</th><th>Сумма</th><th>Поступление</th><th>Действия</th></tr></thead><tbody>{[...state.purchases].reverse().map((p)=>{const complete=p.lines.every((l)=>receivedQuantity(state,p.id,l.itemId)>=l.quantity);return <tr key={p.id}><td>{p.number}<small>{p.date}</small></td><td>{state.suppliers.find((s)=>s.id===p.supplierId)?.name}</td><td>{p.dueDate||'Без срока'}</td><td>{money(p.lines.reduce((n,l)=>n+l.quantity*l.price,0))}</td><td>{complete?'Получено':p.lines.some((l)=>receivedQuantity(state,p.id,l.itemId)>0)?'Частично':'Ожидается'}</td><td><div className="row-actions"><button className="text-link" onClick={()=>setReport(docReport(p))}>Печать</button><button className="text-link" disabled={complete} onClick={()=>setModal({type:'movement',kind:'receipt',purchase:p})}>Принять</button></div></td></tr>;})}</tbody></table>{!state.purchases.length?<Empty title="Закупок пока нет">Добавьте поставщика и оформите заказ материалов.</Empty>:null}</div></>:null}
    {tab==='documents'?<><div className="toolbar"><button className="button primary" onClick={()=>setModal({type:'movement',kind:'receipt'})}>Новое движение</button><button className="button" onClick={()=>downloadCSV('Журнал движений',['Номер','Дата','Вид','Контрагент / получатель','Сумма'],filteredDocs.map((d)=>[d.number,d.date,documentTypes[d.kind],d.target,d.total]))}>Экспорт журнала</button></div><div className="table-wrap"><table><thead><tr><th>Документ</th><th>Вид</th><th>Поставщик / получатель</th><th>Основание</th><th>Сумма</th><th/></tr></thead><tbody>{filteredDocs.map((d)=><tr key={d.id}><td>{d.number}<small>{d.date}</small></td><td>{documentTypes[d.kind]}</td><td>{d.target}</td><td>{d.reference || '—'}</td><td>{money(d.total)}</td><td><button className="text-link" onClick={()=>setReport(docReport(d))}>Открыть / печать</button></td></tr>)}</tbody></table>{!filteredDocs.length?<Empty title="Движений ещё нет"/>:null}</div></>:null}
    {tab==='tools'?<><div className="toolbar"><button className="button primary" onClick={()=>setModal({type:'tool'})}>Добавить инструмент</button><button className="button" onClick={()=>setReport({title:'Реестр инструмента',subtitle:dateKey(),headers:['Номер','Инструмент','Назначение','У кого'],rows:state.tools.map((t)=>[t.serial,t.name,t.home==='production'?'Производство':'Выездной монтаж',holderName(state,t)])})}>Печать реестра</button></div><div className="table-wrap"><table><thead><tr><th>Инструмент</th><th>Назначение</th><th>У кого</th><th>Возврат до</th><th>Действия</th></tr></thead><tbody>{state.tools.filter((t)=>`${t.name} ${t.serial}`.toLowerCase().includes(search.toLowerCase())).map((t)=><tr key={t.id}><td><strong>{t.name}</strong><small>{t.serial}</small></td><td>{t.home==='production'?'Производство':'Выездной монтаж'}</td><td>{holderName(state,t)}</td><td>{t.dueDate||'—'}</td><td><div className="row-actions"><button className="text-link" onClick={()=>setModal({type:'tool',item:t})}>Изменить</button><button className="text-link" onClick={()=>setModal({type:'transfer',item:t})}>{t.holderId?'Вернуть':'Выдать'}</button><button className="text-link" onClick={()=>setReport({title:`Карточка инструмента ${t.serial}`,subtitle:t.name,headers:['Дата','Действие','Получатель','Вернуть до','Примечание'],rows:state.toolEvents.filter((e)=>e.toolId===t.id).map((e)=>[e.date,e.kind==='issue'?'Выдача':'Возврат',e.holder,e.dueDate,e.note])})}>История / печать</button></div></td></tr>)}</tbody></table>{!state.tools.length?<Empty title="Добавьте производственный и выездной инструмент"/>:null}</div></>:null}
    {modal?<Dialog key={modal.type+(modal.item?.id||'')} title={{material:'Карточка материала',supplier:'Поставщик',purchase:'Новая закупка',movement:'Движение материалов',tool:'Карточка инструмента',transfer:modal.item?.holderId?'Возврат инструмента':'Выдача инструмента'}[modal.type]} onClose={close} wide={['purchase','movement'].includes(modal.type)}>
      {modal.type==='material'?<EntryForm onClose={close} onSubmit={(p)=>commit('material.save',{...p,id:modal.item?.id,tracked:p.tracked==='on'})}><Field label="Материал *" wide><input name="name" required defaultValue={modal.item?.name}/></Field><Field label="Категория *"><input name="category" required defaultValue={modal.item?.category||'Материалы'}/></Field><Field label="Единица *"><input name="unit" required defaultValue={modal.item?.unit||'шт'}/></Field><Field label="Текущая цена"><input name="price" type="number" min="0" step="0.01" required defaultValue={modal.item?.price||0}/></Field><Field label="Минимальный запас"><input name="minStock" type="number" min="0" step="0.01" required defaultValue={modal.item?.minStock||0}/></Field><label className="check-row field-wide"><input name="tracked" type="checkbox" defaultChecked={modal.item?.tracked}/>Вести складской учёт</label></EntryForm>:null}
      {modal.type==='supplier'?<EntryForm onClose={close} onSubmit={(p)=>commit('supplier.save',{...p,id:modal.item?.id})}><Field label="Название поставщика *" wide><input name="name" required defaultValue={modal.item?.name}/></Field><Field label="Контакт" wide><input name="contact" defaultValue={modal.item?.contact}/></Field><Field label="Примечание" wide><textarea name="notes" defaultValue={modal.item?.notes}/></Field></EntryForm>:null}
      {modal.type==='purchase'||modal.type==='movement'?<DocumentForm state={state} modal={modal} onClose={close} onSubmit={(p)=>commit(modal.type==='purchase'?'purchase.create':'stock.post',p)}/>:null}
      {modal.type==='tool'?<EntryForm onClose={close} onSubmit={(p)=>commit('tool.save',{...p,id:modal.item?.id})}><Field label="Название инструмента *" wide><input name="name" required defaultValue={modal.item?.name}/></Field><Field label="Инвентарный номер *"><input name="serial" required defaultValue={modal.item?.serial}/></Field><Field label="Назначение"><select name="home" defaultValue={modal.item?.home||'production'}><option value="production">Производство</option><option value="field">Выездной монтаж</option></select></Field><Field label="Стоимость"><input name="price" required type="number" min="0" step="0.01" defaultValue={modal.item?.price||0}/></Field><Field label="Примечание" wide><textarea name="note" defaultValue={modal.item?.note}/></Field></EntryForm>:null}
      {modal.type==='transfer'?<TransferForm state={state} tool={modal.item} onClose={close} onSubmit={(p)=>commit('tool.transfer',p)}/>:null}
    </Dialog>:null}{report?<Report report={report} onClose={()=>setReport(null)}/>:null}
  </section>;
}
function holderName(state,tool) { return tool.holderId ? (tool.holderType==='crew'?state.crews:state.employees).find((p)=>p.id===tool.holderId)?.name || 'Не найден' : 'На базе'; }
function TransferForm({state,tool,onClose,onSubmit}) {
  const [holderType,setHolderType]=useState('crew');
  return <EntryForm onClose={onClose} onSubmit={(p)=>onSubmit({...p,id:tool.id,holderType,kind:tool.holderId?'return':'issue'})}><p className="field-wide">{tool.name} · {tool.serial} · {holderName(state,tool)}</p><Field label="Дата"><input name="date" type="date" required defaultValue={dateKey()}/></Field>{!tool.holderId?<><Field label="Кому"><select value={holderType} onChange={(e)=>setHolderType(e.target.value)}><option value="crew">Бригаде</option><option value="employee">Сотруднику</option></select></Field><Field label="Получатель *" wide><select key={holderType} name="holderId" required><option value="">Выберите получателя</option>{(holderType==='crew'?state.crews:state.employees).filter((p)=>p.active).map((p)=><option value={p.id} key={p.id}>{p.name}</option>)}</select></Field><Field label="Плановый возврат"><input name="dueDate" type="date"/></Field></>:null}<Field label="Примечание / состояние" wide><textarea name="note"/></Field></EntryForm>;
}
function DocumentForm({state,modal,onClose,onSubmit}) {
  const purchasing=modal.type==='purchase'; const [kind,setKind]=useState(modal.kind||'receipt'); const [filter,setFilter]=useState('');
  const purchase=modal.purchase;
  const [lines,setLines]=useState(()=>purchase?purchase.lines.map((l)=>({...l,quantity:l.quantity-receivedQuantity(state,purchase.id,l.itemId)})).filter((l)=>l.quantity>0):[{itemId:'',quantity:1,price:0}]);
  const update=(index,patch)=>setLines((rows)=>rows.map((line,i)=>i===index?{...line,...patch}:line));
  const candidates=state.materials.filter((m)=>(purchasing||kind==='direct'||m.tracked)&&(!purchase||purchase.lines.some((l)=>l.itemId===m.id)));
  return <EntryForm onClose={onClose} label={purchasing?'Создать закупку':'Провести документ'} onSubmit={(p)=>onSubmit({...p,kind,lines,purchaseId:purchase?.id||'',updatePrice:p.updatePrice==='on',target:p.target||state.suppliers.find((s)=>s.id===p.supplierId)?.name||''})}>
    {!purchasing?<Field label="Операция"><select value={kind} onChange={(e)=>setKind(e.target.value)}>{Object.entries(documentTypes).filter(([key])=>!purchase||['receipt','direct'].includes(key)).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field>:null}
    <Field label="Дата документа"><input name="date" type="date" required defaultValue={dateKey()}/></Field>
    <Field label="Поставщик"><select name="supplierId" required={purchasing} defaultValue={purchase?.supplierId||''}><option value="">Без поставщика</option>{state.suppliers.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>
    {purchasing?<Field label="Ожидаемая поставка"><input name="dueDate" type="date"/></Field>:<><Field label="Получатель / основание"><input name="target" required={!['receipt','direct'].includes(kind)} placeholder="Цех, объект, бригада или поставщик"/></Field><Field label="Заказ / объект"><select name="orderId"><option value="">Общий учёт</option>{state.orders.map((o)=><option key={o.id} value={o.id}>{o.number} · {state.sites.find((s)=>s.id===o.siteId)?.name}</option>)}</select></Field><Field label="Накладная / основание"><input name="reference" placeholder="Номер документа поставщика"/></Field></>}
    <Field label="Поиск позиции в списках" wide><input value={filter} onChange={(e)=>setFilter(e.target.value)} placeholder="Название или код материала"/></Field>
    <div className="field-wide document-lines">{lines.map((line,index)=>{const item=state.materials.find((m)=>m.id===line.itemId);return <div className="document-line" key={index}><Field label={`Материал ${index+1}`}><select required value={line.itemId} onChange={(e)=>{const m=state.materials.find((v)=>v.id===e.target.value);update(index,{itemId:e.target.value,price:m?.price||0});}}><option value="">Выберите материал</option>{candidates.filter((m)=>m.id===line.itemId||`${m.name} ${m.id}`.toLowerCase().includes(filter.toLowerCase())).map((m)=><option key={m.id} value={m.id}>{m.name} · {m.unit}</option>)}</select></Field><Field label="Количество"><input aria-label={`Количество ${index+1}`} type="number" min="0.01" step="0.01" required value={line.quantity} onChange={(e)=>update(index,{quantity:e.target.value})}/></Field><Field label={['issue','writeoff'].includes(kind)&&!purchasing?'Средняя себестоимость':'Цена'}><input aria-label={`Цена ${index+1}`} type="number" min="0" step="0.01" required disabled={!purchasing&&['issue','writeoff'].includes(kind)} value={!purchasing&&['issue','writeoff'].includes(kind)?stockFor(state,line.itemId).average:line.price} onChange={(e)=>update(index,{price:e.target.value})}/></Field><button className="icon-button" type="button" aria-label={`Удалить строку ${index+1}`} disabled={lines.length===1} onClick={()=>setLines(lines.filter((_,i)=>i!==index))}>×</button>{item?.tracked?<small>На складе: {stockFor(state,item.id).quantity} {item.unit}</small>:null}</div>;})}<button className="button" type="button" onClick={()=>setLines([...lines,{itemId:'',quantity:1,price:0}])}>Добавить строку</button></div>
    {!purchasing&&['receipt','direct'].includes(kind)?<label className="check-row field-wide"><input name="updatePrice" type="checkbox" defaultChecked/>Обновить общий прайс по ценам поступления</label>:null}
    <Field label="Примечание" wide><textarea name="note"/></Field><p className="form-hint field-wide">{purchasing?'Полученные количества учитываются по приходам. Допускается частичная поставка.':'Проведённый документ сохраняется в истории. Расход оценивается по средней себестоимости. «Покупка на объект» не увеличивает складской остаток.'}</p>
  </EntryForm>;
}
