import { useEffect, useRef, useState } from 'react';
import { Ban, Check, ClipboardList, EllipsisVertical, ExternalLink, FileText, Link2, PackageCheck, Pencil, Plus, Printer, RotateCcw, ShoppingCart, Wrench } from 'lucide-react';
import { Dialog, Field, PageHeading, Empty } from '../components/UI.jsx';
import { EntryForm, Report, SectionTabs, downloadCSV } from '../components/OperationsUI.jsx';
import { dateKey } from '../app/model.js';
import { documentTypes, money, stockFor, receivedQuantity, PRICE_SOURCE, exportCalculatorPrices } from '../app/operations.js';

const tabs = [['needs','Потребности'],['stock','Склад'],['catalog','Общий прайс'],['purchases','Закупки'],['documents','Движения'],['forms','Бланки'],['tools','Инструмент'],['suppliers','Поставщики']];
const needKinds = { tool:'Инструмент', consumable:'Расходные материалы', equipment:'Оборудование', other:'Другое' };
const needStatuses = { requested:'Заявлено', approved:'Согласовано', ordered:'Товар заказан', received:'Получено', rejected:'Отказано', cancelled:'Отменено' };
const needPriorities = { normal:'Обычный', high:'Высокий', urgent:'Срочно' };
export function Inventory({ state, command, search }) {
  const [tab, setTab] = useState('needs'); const [modal, setModal] = useState(null); const [report, setReport] = useState(null); const [query,setQuery] = useState(''); const [category,setCategory] = useState(''); const [notice,setNotice] = useState('');
  const close = () => setModal(null);
  async function commit(action,payload) { await command(action,payload); close(); setNotice('Сохранено в базе данных'); }
  async function updateNeedStatus(item,status) { try { await command('need.save',{...item,status}); setNotice(`«${item.name}»: ${needStatuses[status].toLowerCase()}. Сохранено в базе данных.`); } catch (error) { setNotice(`Не сохранено: ${error.message}`); } }
  const stocks = new Map(state.materials.map((m) => [m.id,stockFor(state,m.id)]));
  const materials = state.materials.filter((m) => (tab !== 'stock' || m.tracked) && (!category || m.category === category) && `${m.id} ${m.name} ${m.category}`.toLowerCase().includes(`${search} ${query}`.trim().toLowerCase()));
  const totalValue = [...stocks.values()].reduce((n,s) => n+s.value,0);
  const filteredDocs = [...state.stockDocuments].reverse().filter((d) => `${d.number} ${d.target} ${d.reference} ${d.lines.map((l)=>l.name).join(' ')}`.toLowerCase().includes(search.toLowerCase()));
  const needs = state.supplyNeeds.filter((item)=>`${item.name} ${needKinds[item.kind]} ${item.destination} ${item.requestedBy} ${item.note}`.toLowerCase().includes(search.toLowerCase()));
  const printableForms = buildPrintableForms(state,stocks);
  function exportPrice(){const url=URL.createObjectURL(new Blob([JSON.stringify(exportCalculatorPrices(state),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='Прайс-лист_ЭФТ_CRM_v12.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const stockReport = () => ({ title: tab === 'stock' ? 'Ведомость складских остатков' : 'Прайс-лист материалов', subtitle: `На ${dateKey()} · ${PRICE_SOURCE}`, headers:['Код','Материал','Ед.','Остаток','Текущая цена','Стоимость остатка'], rows:materials.map((m)=>[m.id,m.name,m.unit,stocks.get(m.id).quantity,money(m.price),money(stocks.get(m.id).value)]) });
  function docReport(doc) { return { title:`${documentTypes[doc.kind] || 'Заказ поставщику'} ${doc.number}`, subtitle:`${doc.date} · ${doc.target || state.suppliers.find((s)=>s.id===doc.supplierId)?.name || ''} · ${doc.reference || ''}`, headers:['Материал','Ед.','Количество','Цена','Сумма'], rows:doc.lines.map((l)=>[l.name,l.unit,l.quantity,money(l.price),money(l.quantity*l.price)]), footer:`Итого: ${money(doc.lines.reduce((n,l)=>n+l.quantity*l.price,0))}. ${doc.note || ''}` }; }
  return <section className="page"><PageHeading title="Закупки и склад" description="Материалы, поступления, расход и инструмент" /><div className="ops-metrics"><div><strong>{state.materials.filter((m)=>m.tracked).length}</strong><span>позиций на складском учёте</span></div><div><strong>{money(totalValue)}</strong><span>стоимость остатка</span></div><div><strong>{state.materials.filter((m)=>m.tracked && stocks.get(m.id).quantity<m.minStock).length}</strong><span>ниже минимального запаса</span></div></div><SectionTabs items={tabs} value={tab} onChange={(value)=>{setTab(value);setQuery('');setCategory('');setNotice('');}} />{notice ? <p className="inline-notice" role="status">{notice}</p>:null}
    {tab==='needs'?<><div className="toolbar"><button className="button primary" onClick={()=>setModal({type:'need'})}><Plus size={16}/>Добавить потребность</button><button className="button" onClick={()=>setReport({title:'Потребности производства и ТП',subtitle:dateKey(),headers:['Потребность','Вид','Подразделение','Количество','Приоритет','Нужно к','Статус'],rows:needs.map((item)=>[item.name,needKinds[item.kind],item.destination==='production'?'Производство':'ТП',`${item.quantity} ${item.unit}`,needPriorities[item.priority],item.neededBy||'Без срока',needStatuses[item.status]||item.status])})}><Printer size={16}/>Печать</button></div><p className="ops-hint">Инструмент, оборудование и расходные материалы для производства и ТП, которые не входят в домокомплекты.</p><div className="need-summary"><span><strong>{state.supplyNeeds.filter((item)=>!['received','rejected','cancelled'].includes(item.status)).length}</strong> открыто</span><span><strong>{state.supplyNeeds.filter((item)=>item.priority==='urgent'&&!['received','rejected','cancelled'].includes(item.status)).length}</strong> срочно</span><span><strong>{state.supplyNeeds.filter((item)=>item.status==='ordered').length}</strong> заказано</span></div><div className="table-wrap needs-table-wrap"><table className="needs-table"><thead><tr><th>Потребность</th><th>Для кого</th><th>Количество</th><th>Приоритет</th><th>Нужно к</th><th>Статус</th><th>Ссылки</th><th>Действия</th></tr></thead><tbody>{needs.map((item)=><tr key={item.id}><td><strong>{item.name}</strong><small>{needKinds[item.kind]}{item.requestedBy?` · ${item.requestedBy}`:''}</small>{item.note?<small>{item.note}</small>:null}</td><td>{item.destination==='production'?'Производство':'ТП'}</td><td>{item.quantity} {item.unit}</td><td><span className={`need-priority ${item.priority}`}>{needPriorities[item.priority]}</span></td><td>{item.neededBy||'Без срока'}</td><td><span className={`need-status ${item.status}`}>{needStatuses[item.status]||item.status}</span></td><td>{item.links.length?<div className="need-links">{item.links.map((link,index)=><a key={link} href={link} target="_blank" rel="noreferrer" title={link}><ExternalLink size={13}/>Ссылка {index+1}</a>)}</div>:'—'}</td><td><NeedActions item={item} onEdit={()=>setModal({type:'need',item})} onStatus={(status)=>updateNeedStatus(item,status)}/></td></tr>)}</tbody></table>{!needs.length?<Empty title="Потребностей пока нет">Добавьте инструмент или расходные материалы для снабжения производства и ТП.</Empty>:null}</div></>:null}
    {['stock','catalog'].includes(tab) ? <><div className="toolbar"><input aria-label="Найти материал" placeholder="Название, категория, код" value={query} onChange={(e)=>setQuery(e.target.value)} /><select aria-label="Категория материалов" value={category} onChange={(e)=>setCategory(e.target.value)}><option value="">Все категории</option>{[...new Set(state.materials.map((m)=>m.category))].map((c)=><option key={c}>{c}</option>)}</select><button className="button" onClick={()=>setModal({type:'material'})}><Plus size={16}/>Материал</button><button className="button" onClick={()=>setReport(stockReport())}><Printer size={16}/>Печать</button>{tab==='catalog'?<button className="button" onClick={exportPrice}>Экспорт для калькулятора</button>:null}{tab==='stock'?<><button className="button primary" onClick={()=>setModal({type:'movement',kind:'receipt'})}>Приход</button><button className="button" onClick={()=>setModal({type:'movement',kind:'issue'})}>Расход</button></>:null}</div><p className="ops-hint">{tab==='stock'?'Остатки формируются из проведённых движений. Отметьте нужные позиции в общем прайсе для складского учёта.':'Исходный прайс из калькулятора. Цена обновляется при поступлении; ранее проведённые документы сохраняют свои суммы. Автоматический обмен с калькулятором ещё не подключён.'} Показано {materials.length} позиций одним списком.</p><div className="table-wrap material-sheet"><table><thead><tr><th>Материал</th><th>Ед.</th><th>Цена</th><th>Остаток</th><th>Мин. запас</th><th>Учёт</th><th>Действия</th></tr></thead><tbody>{materials.map((m)=><tr key={m.id}><td><strong>{m.name}</strong><small>{m.id} · {m.category}{m.priceNote ? ` · ${m.priceNote}` : ''}</small></td><td>{m.unit}</td><td>{money(m.price)}</td><td className={stocks.get(m.id).quantity<m.minStock?'amber-text':''}>{m.tracked?stocks.get(m.id).quantity:'—'}</td><td>{m.minStock}</td><td>{m.tracked?'Склад':'Под заказ'}</td><td><button className="text-link" onClick={()=>setModal({type:'material',item:m})}>Изменить</button></td></tr>)}</tbody></table>{!materials.length?<Empty title="Материалов пока нет">Откройте общий прайс и включите складской учёт нужных позиций.</Empty>:null}</div></>:null}
    {tab==='suppliers'?<><div className="toolbar"><button className="button primary" onClick={()=>setModal({type:'supplier'})}>Добавить поставщика</button></div><div className="table-wrap"><table><thead><tr><th>Поставщик</th><th>Контакты</th><th>Примечание</th><th/></tr></thead><tbody>{state.suppliers.map((s)=><tr key={s.id}><td>{s.name}</td><td>{s.contact}</td><td>{s.notes}</td><td><button className="text-link" onClick={()=>setModal({type:'supplier',item:s})}>Изменить</button></td></tr>)}</tbody></table>{!state.suppliers.length?<Empty title="Добавьте поставщиков материалов"/>:null}</div></>:null}
    {tab==='purchases'?<><div className="toolbar"><button className="button primary" onClick={()=>setModal({type:'purchase'})}>Новая закупка</button></div><div className="table-wrap"><table><thead><tr><th>Документ</th><th>Поставщик</th><th>Срок</th><th>Сумма</th><th>Поступление</th><th>Действия</th></tr></thead><tbody>{[...state.purchases].reverse().map((p)=>{const complete=p.lines.every((l)=>receivedQuantity(state,p.id,l.itemId)>=l.quantity);return <tr key={p.id}><td>{p.number}<small>{p.date}</small></td><td>{state.suppliers.find((s)=>s.id===p.supplierId)?.name}</td><td>{p.dueDate||'Без срока'}</td><td>{money(p.lines.reduce((n,l)=>n+l.quantity*l.price,0))}</td><td>{complete?'Получено':p.lines.some((l)=>receivedQuantity(state,p.id,l.itemId)>0)?'Частично':'Ожидается'}</td><td><div className="row-actions"><button className="text-link" onClick={()=>setReport(docReport(p))}>Печать</button><button className="text-link" disabled={complete} onClick={()=>setModal({type:'movement',kind:'receipt',purchase:p})}>Принять</button></div></td></tr>;})}</tbody></table>{!state.purchases.length?<Empty title="Закупок пока нет">Добавьте поставщика и оформите заказ материалов.</Empty>:null}</div></>:null}
    {tab==='documents'?<><div className="toolbar"><button className="button primary" onClick={()=>setModal({type:'movement',kind:'receipt'})}>Новое движение</button><button className="button" onClick={()=>downloadCSV('Журнал движений',['Номер','Дата','Вид','Контрагент / получатель','Сумма'],filteredDocs.map((d)=>[d.number,d.date,documentTypes[d.kind],d.target,d.total]))}>Экспорт журнала</button></div><div className="table-wrap"><table><thead><tr><th>Документ</th><th>Вид</th><th>Поставщик / получатель</th><th>Основание</th><th>Сумма</th><th/></tr></thead><tbody>{filteredDocs.map((d)=><tr key={d.id}><td>{d.number}<small>{d.date}</small></td><td>{documentTypes[d.kind]}</td><td>{d.target}</td><td>{d.reference || '—'}</td><td>{money(d.total)}</td><td><button className="text-link" onClick={()=>setReport(docReport(d))}>Открыть / печать</button></td></tr>)}</tbody></table>{!filteredDocs.length?<Empty title="Движений ещё нет"/>:null}</div></>:null}
    {tab==='forms'?<><p className="ops-hint">Печатные формы можно заполнить на компьютере позднее или распечатать пустыми для ручного заполнения. Инвентаризационная ведомость уже содержит текущие остатки CRM.</p><div className="print-form-grid">{printableForms.map((form)=><article className="print-form-card" key={form.id}><div className="print-form-icon">{form.icon==='tool'?<Wrench size={21}/>:form.icon==='list'?<ClipboardList size={21}/>:<FileText size={21}/>}</div><div><h3>{form.title}</h3><p>{form.description}</p><small>{form.report.rows.length} строк · формат A4</small></div><button className="button" onClick={()=>setReport(form.report)}><Printer size={15}/>Открыть и печатать</button></article>)}</div></>:null}
    {tab==='tools'?<><div className="toolbar"><button className="button primary" onClick={()=>setModal({type:'tool'})}>Добавить инструмент</button><button className="button" onClick={()=>setReport({title:'Реестр инструмента',subtitle:dateKey(),headers:['Номер','Инструмент','Назначение','У кого'],rows:state.tools.map((t)=>[t.serial,t.name,t.home==='production'?'Производство':'Выездной монтаж',holderName(state,t)])})}>Печать реестра</button></div><div className="table-wrap"><table><thead><tr><th>Инструмент</th><th>Назначение</th><th>У кого</th><th>Возврат до</th><th>Действия</th></tr></thead><tbody>{state.tools.filter((t)=>`${t.name} ${t.serial}`.toLowerCase().includes(search.toLowerCase())).map((t)=><tr key={t.id}><td><strong>{t.name}</strong><small>{t.serial}</small></td><td>{t.home==='production'?'Производство':'Выездной монтаж'}</td><td>{holderName(state,t)}</td><td>{t.dueDate||'—'}</td><td><div className="row-actions"><button className="text-link" onClick={()=>setModal({type:'tool',item:t})}>Изменить</button><button className="text-link" onClick={()=>setModal({type:'transfer',item:t})}>{t.holderId?'Вернуть':'Выдать'}</button><button className="text-link" onClick={()=>setReport(toolAct(t))}>Бланк выдачи</button><button className="text-link" onClick={()=>setReport({title:`Карточка инструмента ${t.serial}`,subtitle:t.name,headers:['Дата','Действие','Получатель','Вернуть до','Примечание'],rows:state.toolEvents.filter((e)=>e.toolId===t.id).map((e)=>[e.date,e.kind==='issue'?'Выдача':'Возврат',e.holder,e.dueDate,e.note])})}>История / печать</button></div></td></tr>)}</tbody></table>{!state.tools.length?<Empty title="Добавьте производственный и выездной инструмент"/>:null}</div></>:null}
    {modal?<Dialog key={modal.type+(modal.item?.id||'')} title={{need:modal.item?'Изменить потребность':'Новая потребность',material:'Карточка материала',supplier:'Поставщик',purchase:'Новая закупка',movement:'Движение материалов',tool:'Карточка инструмента',transfer:modal.item?.holderId?'Возврат инструмента':'Выдача инструмента'}[modal.type]} onClose={close} wide={['purchase','movement','need'].includes(modal.type)}>
      {modal.type==='need'?<NeedForm state={state} item={modal.item} onClose={close} onSubmit={(p)=>commit('need.save',p)}/>:null}
      {modal.type==='material'?<EntryForm onClose={close} onSubmit={(p)=>commit('material.save',{...p,id:modal.item?.id,tracked:p.tracked==='on'})}><Field label="Материал *" wide><input name="name" required defaultValue={modal.item?.name}/></Field><Field label="Категория *"><input name="category" required defaultValue={modal.item?.category||'Материалы'}/></Field><Field label="Единица *"><input name="unit" required defaultValue={modal.item?.unit||'шт'}/></Field><Field label="Текущая цена"><input name="price" type="number" min="0" step="0.01" required defaultValue={modal.item?.price||0}/></Field><Field label="Минимальный запас"><input name="minStock" type="number" min="0" step="0.01" required defaultValue={modal.item?.minStock||0}/></Field><label className="check-row field-wide"><input name="tracked" type="checkbox" defaultChecked={modal.item?.tracked}/>Вести складской учёт</label></EntryForm>:null}
      {modal.type==='supplier'?<EntryForm onClose={close} onSubmit={(p)=>commit('supplier.save',{...p,id:modal.item?.id})}><Field label="Название поставщика *" wide><input name="name" required defaultValue={modal.item?.name}/></Field><Field label="Контакт" wide><input name="contact" defaultValue={modal.item?.contact}/></Field><Field label="Примечание" wide><textarea name="notes" defaultValue={modal.item?.notes}/></Field></EntryForm>:null}
      {modal.type==='purchase'||modal.type==='movement'?<DocumentForm state={state} modal={modal} onClose={close} onAddSupplier={async(name)=>{try{await command('supplier.save',{name,contact:'',notes:''});setNotice(`Контрагент «${name}» сохранён в базе данных`);}catch(error){setNotice(`Не сохранено: ${error.message}`);}}} onSubmit={(p)=>commit(modal.type==='purchase'?'purchase.create':'stock.post',p)}/>:null}
      {modal.type==='tool'?<EntryForm onClose={close} onSubmit={(p)=>commit('tool.save',{...p,id:modal.item?.id})}><Field label="Название инструмента *" wide><input name="name" required defaultValue={modal.item?.name}/></Field><Field label="Инвентарный номер *"><input name="serial" required defaultValue={modal.item?.serial}/></Field><Field label="Назначение"><select name="home" defaultValue={modal.item?.home||'production'}><option value="production">Производство</option><option value="field">Выездной монтаж</option></select></Field><Field label="Стоимость"><input name="price" required type="number" min="0" step="0.01" defaultValue={modal.item?.price||0}/></Field><Field label="Примечание" wide><textarea name="note" defaultValue={modal.item?.note}/></Field></EntryForm>:null}
      {modal.type==='transfer'?<TransferForm state={state} tool={modal.item} onClose={close} onSubmit={(p)=>commit('tool.transfer',p)}/>:null}
    </Dialog>:null}{report?<Report report={report} onClose={()=>setReport(null)}/>:null}
  </section>;
}
const needActions = [
  ['approved','Согласовать',Check],
  ['ordered','Товар заказан',ShoppingCart],
  ['received','Товар получен',PackageCheck],
  ['rejected','Отказать',Ban],
  ['requested','Вернуть в заявки',RotateCcw],
];
function NeedActions({item,onEdit,onStatus}) {
  const [open,setOpen]=useState(false); const root=useRef(null);
  useEffect(()=>{if(!open)return;const close=(event)=>{if(event.type==='keydown'&&event.key!=='Escape')return;if(event.type==='pointerdown'&&root.current?.contains(event.target))return;setOpen(false);};document.addEventListener('pointerdown',close);document.addEventListener('keydown',close);window.addEventListener('scroll',close,true);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',close);window.removeEventListener('scroll',close,true);};},[open]);
  const choose=(action)=>{setOpen(false);action();};
  return <div className="row-action-menu" ref={root}><button type="button" className="icon-button" aria-label={`Действия: ${item.name}`} title="Действия" aria-expanded={open} onClick={()=>setOpen((value)=>!value)}><EllipsisVertical size={18}/></button>{open?<div className="row-action-popover" role="menu"><button type="button" role="menuitem" onClick={()=>choose(onEdit)}><Pencil size={15}/>Изменить</button>{needActions.filter(([status])=>status!==item.status).map(([status,label,Icon])=><button type="button" role="menuitem" className={status==='rejected'?'danger':''} key={status} onClick={()=>choose(()=>onStatus(status))}><Icon size={15}/>{label}</button>)}</div>:null}</div>;
}
function NeedForm({state,item,onClose,onSubmit}) {
  const [links,setLinks]=useState(item?.links?.length?item.links:['']);
  const updateLink=(index,value)=>setLinks((current)=>current.map((link,i)=>i===index?value:link));
  return <EntryForm onClose={onClose} label={item?'Сохранить изменения':'Добавить потребность'} onSubmit={(payload)=>onSubmit({...payload,id:item?.id,links:links.map((link)=>link.trim()).filter(Boolean)})}>
    <Field label="Что необходимо *" wide><input name="name" required maxLength={300} defaultValue={item?.name||''} autoFocus placeholder="Например, диски для циркулярной пилы"/></Field>
    <Field label="Вид"><select name="kind" defaultValue={item?.kind||'consumable'}>{Object.entries(needKinds).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></Field>
    <Field label="Для кого"><select name="destination" defaultValue={item?.destination||'production'}><option value="production">Производство</option><option value="tp">ТП</option></select></Field>
    <Field label="Количество *"><input name="quantity" type="number" min="0.01" step="0.01" required defaultValue={item?.quantity||1}/></Field>
    <Field label="Единица *"><input name="unit" required maxLength={50} defaultValue={item?.unit||'шт'} list="need-units"/><datalist id="need-units"><option value="шт"/><option value="упак"/><option value="компл"/><option value="л"/><option value="кг"/><option value="м"/></datalist></Field>
    <Field label="Приоритет"><select name="priority" defaultValue={item?.priority||'normal'}>{Object.entries(needPriorities).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></Field>
    <Field label="Нужно к дате"><input name="neededBy" type="date" defaultValue={item?.neededBy||''}/></Field>
    <Field label="Статус"><select name="status" defaultValue={item?.status||'requested'}>{Object.entries(needStatuses).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></Field>
    <Field label="Кто запросил"><select name="requestedBy" defaultValue={item?.requestedBy||''}><option value="">Не указан</option>{state.employees.filter((person)=>person.active).map((person)=><option key={person.id} value={person.name}>{person.name} · {person.role}</option>)}</select></Field>
    <div className="field-wide need-link-editor"><span>Ссылки для заказа</span>{links.map((link,index)=><div key={index}><Link2 size={16}/><input type="url" aria-label={`Ссылка ${index+1}`} value={link} onChange={(event)=>updateLink(index,event.target.value)} placeholder="https://магазин.рф/товар"/><button className="icon-button" type="button" aria-label={`Удалить ссылку ${index+1}`} disabled={links.length===1} onClick={()=>setLinks((current)=>current.filter((_,i)=>i!==index))}>×</button></div>)}<button className="text-link" type="button" disabled={links.length>=10} onClick={()=>setLinks((current)=>[...current,''])}><Plus size={14}/>Добавить ещё ссылку</button></div>
    <Field label="Комментарий" wide><textarea name="note" rows={3} maxLength={2000} defaultValue={item?.note||''} placeholder="Характеристики, предпочтительный магазин, причина закупки"/></Field>
    <p className="form-hint field-wide">Потребность ведётся отдельно от материалов домокомплектов. После заказа измените статус на «Заказано», после получения — на «Получено».</p>
  </EntryForm>;
}
const emptyRows=(count,columns)=>Array.from({length:count},(_,index)=>[index+1,...Array(columns-1).fill('')]);
const commonFields=()=>[['Дата',dateKey()],['Подразделение / объект',''],['Ответственный','']];
function toolAct(tool) {
  const rows=tool?[[1,tool.name,tool.serial,1,'Исправен',''],...emptyRows(5,6).map((row,index)=>[index+2,...row.slice(1)])]:emptyRows(12,6);
  return {title:'Акт выдачи инструмента',subtitle:'Бланк приёма-передачи материальных ценностей',manual:true,fields:[['Дата выдачи',dateKey()],['Получатель / бригада',''],['Объект',''],['Плановая дата возврата','']],headers:['№','Инструмент','Инвентарный №','Кол-во','Состояние при выдаче','Состояние при возврате'],rows,footer:'Получатель принимает ответственность за сохранность и обязуется сообщить о неисправности или утрате.',signatureLabels:['Выдал','Получил','Вернул','Принял']};
}
function buildPrintableForms(state,stocks) {
  const inventoryRows=state.materials.filter((item)=>item.tracked).map((item,index)=>[index+1,item.name,item.id,item.unit,stocks.get(item.id)?.quantity??0,'','']);
  return [
    {id:'purchase-request',title:'Заявка на закупку',description:'Инструмент, оборудование, расходные материалы и хозяйственные нужды.',icon:'list',report:{title:'Заявка на закупку',subtitle:'Заполняется инициатором и передаётся ответственному за снабжение',manual:true,fields:commonFields(),headers:['№','Наименование и характеристики','Ед.','Кол-во','Нужно к','Ссылка / поставщик','Решение'],rows:emptyRows(15,7),signatureLabels:['Заявитель','Согласовал','Закупщик']}},
    {id:'supplier-comparison',title:'Сравнение поставщиков',description:'Сопоставление цен, сроков, доставки и итоговый выбор.',icon:'list',report:{title:'Лист сравнения предложений поставщиков',subtitle:'Приложение к заявке на закупку',manual:true,fields:[['Заявка №',''],['Дата',dateKey()],['Ответственный','']],headers:['№','Позиция','Поставщик','Цена','Доставка','Срок','Условия оплаты','Выбор'],rows:emptyRows(12,8),signatureLabels:['Подготовил','Согласовал']}},
    {id:'receipt-sheet',title:'Приходная ведомость',description:'Ручная приёмка материалов по накладной поставщика.',icon:'document',report:{title:'Приходная ведомость материалов',subtitle:'Контроль количества и состояния при поступлении',manual:true,fields:[['Дата',dateKey()],['Поставщик',''],['Накладная №',''],['Принял','']],headers:['№','Материал','Ед.','По документу','Фактически','Цена','Повреждения / расхождения'],rows:emptyRows(18,7),signatureLabels:['Сдал','Принял','Проверил']}},
    {id:'material-issue',title:'Выдача материалов',description:'Передача материалов в цех, на объект или монтажной бригаде.',icon:'document',report:{title:'Требование-накладная на выдачу материалов',subtitle:'Списание материалов со склада',manual:true,fields:[['Дата',dateKey()],['Объект / заказ',''],['Получатель / бригада',''],['Основание','']],headers:['№','Материал','Код','Ед.','Количество','Назначение','Примечание'],rows:emptyRows(18,7),signatureLabels:['Отпустил','Получил','Прораб']}},
    {id:'inventory',title:'Инвентаризация склада',description:'Учётные остатки подставляются из CRM, фактические вносятся вручную.',icon:'list',report:{title:'Инвентаризационная ведомость склада',subtitle:`Учётные остатки на ${dateKey()}`,manual:true,fields:[['Склад / зона',''],['Дата проверки',dateKey()],['Комиссия','']],headers:['№','Материал','Код','Ед.','По учёту','Фактически','Отклонение'],rows:inventoryRows.length?inventoryRows:emptyRows(20,7),signatureLabels:['Материально ответственное лицо','Член комиссии','Председатель']}},
    {id:'tool-issue',title:'Выдача инструмента',description:'Фиксация состояния, получателя, срока возврата и подписей.',icon:'tool',report:toolAct()},
    {id:'tool-return',title:'Возврат и осмотр инструмента',description:'Состояние при возврате, комплектность, неисправности и ремонт.',icon:'tool',report:{title:'Акт возврата и осмотра инструмента',subtitle:'Заполняется при возврате на базу или передаче другой бригаде',manual:true,fields:[['Дата возврата',dateKey()],['Сотрудник / бригада',''],['Объект','']],headers:['№','Инструмент','Инвентарный №','Комплектность','Состояние','Неисправность / ремонт'],rows:emptyRows(12,6),footer:'При обнаружении неисправности инструмент передаётся ответственному за ремонт и помечается как недоступный.',signatureLabels:['Сдал','Принял','Ответственный']}},
    {id:'blank-register',title:'Пустой лист учёта',description:'Универсальная таблица для записей на складе, в цехе или на объекте.',icon:'document',report:{title:'Лист учёта',subtitle:'Универсальный бланк для ручного заполнения',manual:true,fields:[['Название журнала',''],...commonFields()],headers:['№','Дата','Наименование / действие','Количество','Ответственный','Подпись','Примечание'],rows:emptyRows(22,7),signatureLabels:['Вёл журнал','Проверил']}},
  ];
}
function holderName(state,tool) { return tool.holderId ? (tool.holderType==='crew'?state.crews:state.employees).find((p)=>p.id===tool.holderId)?.name || 'Не найден' : 'На базе'; }
function TransferForm({state,tool,onClose,onSubmit}) {
  const [holderType,setHolderType]=useState('crew');
  return <EntryForm onClose={onClose} onSubmit={(p)=>onSubmit({...p,id:tool.id,holderType,kind:tool.holderId?'return':'issue'})}><p className="field-wide">{tool.name} · {tool.serial} · {holderName(state,tool)}</p><Field label="Дата"><input name="date" type="date" required defaultValue={dateKey()}/></Field>{!tool.holderId?<><Field label="Кому"><select value={holderType} onChange={(e)=>setHolderType(e.target.value)}><option value="crew">Бригаде</option><option value="employee">Сотруднику</option></select></Field><Field label="Получатель *" wide><select key={holderType} name="holderId" required><option value="">Выберите получателя</option>{(holderType==='crew'?state.crews:state.employees).filter((p)=>p.active).map((p)=><option value={p.id} key={p.id}>{p.name}</option>)}</select></Field><Field label="Плановый возврат"><input name="dueDate" type="date"/></Field></>:null}<Field label="Примечание / состояние" wide><textarea name="note"/></Field></EntryForm>;
}
function DocumentForm({state,modal,onClose,onSubmit,onAddSupplier}) {
  const purchasing=modal.type==='purchase'; const [kind,setKind]=useState(modal.kind||'receipt'); const [filter,setFilter]=useState('');
  const purchase=modal.purchase;
  const [lines,setLines]=useState(()=>purchase?purchase.lines.map((l)=>({...l,quantity:l.quantity-receivedQuantity(state,purchase.id,l.itemId)})).filter((l)=>l.quantity>0):[{itemId:'',quantity:1,price:0}]);
  const update=(index,patch)=>setLines((rows)=>rows.map((line,i)=>i===index?{...line,...patch}:line));
  const candidates=state.materials.filter((m)=>(purchasing||kind==='direct'||m.tracked)&&(!purchase||purchase.lines.some((l)=>l.itemId===m.id)));
  return <EntryForm onClose={onClose} label={purchasing?'Создать закупку':'Провести документ'} onSubmit={(p)=>onSubmit({...p,kind,lines,purchaseId:purchase?.id||'',updatePrice:p.updatePrice==='on',target:p.target||state.suppliers.find((s)=>s.id===p.supplierId)?.name||''})}>
    {!purchasing?<Field label="Операция"><select value={kind} onChange={(e)=>setKind(e.target.value)}>{Object.entries(documentTypes).filter(([key])=>!purchase||['receipt','direct'].includes(key)).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field>:null}
    <Field label="Дата документа"><input name="date" type="date" required defaultValue={dateKey()}/></Field>
    <Field label="Поставщик / контрагент"><select name="supplierId" required={purchasing} defaultValue={purchase?.supplierId||''}><option value="">Без поставщика</option>{state.suppliers.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className="text-link inline-add" type="button" onClick={async()=>{const name=window.prompt('Название нового поставщика или контрагента');if(name?.trim())await onAddSupplier(name.trim());}}>+ Добавить в список</button></Field>
    {purchasing?<Field label="Ожидаемая поставка"><input name="dueDate" type="date"/></Field>:<><Field label="Получатель / основание"><input name="target" required={!['receipt','direct'].includes(kind)} placeholder="Цех, объект, бригада или поставщик"/></Field><Field label="Заказ / объект"><select name="orderId"><option value="">Общий учёт</option>{state.orders.map((o)=><option key={o.id} value={o.id}>{o.number} · {state.sites.find((s)=>s.id===o.siteId)?.name}</option>)}</select></Field><Field label="Накладная / основание"><input name="reference" placeholder="Номер документа поставщика"/></Field></>}
    <Field label="Поиск позиции в списках" wide><input value={filter} onChange={(e)=>setFilter(e.target.value)} placeholder="Название или код материала"/></Field>
    <div className="field-wide document-lines">{lines.map((line,index)=>{const item=state.materials.find((m)=>m.id===line.itemId);return <div className="document-line" key={index}><Field label={`Материал ${index+1}`}><select required value={line.itemId} onChange={(e)=>{const m=state.materials.find((v)=>v.id===e.target.value);update(index,{itemId:e.target.value,price:m?.price||0});}}><option value="">Выберите материал</option>{candidates.filter((m)=>m.id===line.itemId||`${m.name} ${m.id}`.toLowerCase().includes(filter.toLowerCase())).map((m)=><option key={m.id} value={m.id}>{m.name} · {m.unit}</option>)}</select></Field><Field label="Количество"><input aria-label={`Количество ${index+1}`} type="number" min="0.01" step="0.01" required value={line.quantity} onChange={(e)=>update(index,{quantity:e.target.value})}/></Field><Field label={['issue','writeoff'].includes(kind)&&!purchasing?'Средняя себестоимость':'Цена'}><input aria-label={`Цена ${index+1}`} type="number" min="0" step="0.01" required disabled={!purchasing&&['issue','writeoff'].includes(kind)} value={!purchasing&&['issue','writeoff'].includes(kind)?stockFor(state,line.itemId).average:line.price} onChange={(e)=>update(index,{price:e.target.value})}/></Field><button className="icon-button" type="button" aria-label={`Удалить строку ${index+1}`} disabled={lines.length===1} onClick={()=>setLines(lines.filter((_,i)=>i!==index))}>×</button>{item?.tracked?<small>На складе: {stockFor(state,item.id).quantity} {item.unit}</small>:null}</div>;})}<button className="button" type="button" onClick={()=>setLines([...lines,{itemId:'',quantity:1,price:0}])}>Добавить строку</button></div>
    {!purchasing&&['receipt','direct'].includes(kind)?<label className="check-row field-wide"><input name="updatePrice" type="checkbox" defaultChecked/>Обновить общий прайс по ценам поступления</label>:null}
    <Field label="Примечание" wide><textarea name="note"/></Field><p className="form-hint field-wide">{purchasing?'Полученные количества учитываются по приходам. Допускается частичная поставка.':'Проведённый документ сохраняется в истории. Расход оценивается по средней себестоимости. «Покупка на объект» не увеличивает складской остаток.'}</p>
  </EntryForm>;
}
