import { useState } from 'react';
import { Plus, Search, List, Columns3, MoreHorizontal, ArrowUpRight, X, CalendarDays, Pencil, MessageSquare, Factory } from 'lucide-react';
import { Avatar, Badge, Empty, PageHeading, Timeline } from '../components/UI.jsx';
import { LEAD_STAGES, dateLabel, employee, isOverdue, leadContext } from '../app/model.js';

export function Leads({ state, search, selectedId, onSelect, onCreate, onEdit, onChangeStage }) {
  const [owner, setOwner] = useState(''); const [query, setQuery] = useState(''); const [view, setView] = useState('table'); const [stage, setStage] = useState('');
  const leads = state.leads.filter((l) => { const { client, site } = leadContext(state, l); const hay = `${client.name} ${client.phone} ${client.email} ${site.name} ${site.address} ${l.nextAction}`.toLowerCase(); return (!owner || l.ownerId === owner) && (!stage || l.status === stage) && hay.includes(search.toLowerCase()) && hay.includes(query.toLowerCase()); });
  const overdue = state.leads.filter((l) => l.status !== 'lost' && isOverdue(l.dueAt)).length;
  return <section className="page leads-page"><PageHeading title="Заявки" description="От первого обращения до передачи в цех"><button className="button primary" onClick={onCreate}><Plus size={20} />Новая заявка</button></PageHeading>
    <div className="summary-strip"><span><strong>{state.leads.filter((l) => l.status !== 'lost').length}</strong>в работе</span><span><strong className="amber-text">{overdue}</strong>требуют контакта</span><span><strong className="amber-text">{state.leads.filter((l) => l.status === 'contract' && !state.orders.some((o) => o.leadId === l.id)).length}</strong>передать в цех</span></div>
    <div className="toolbar"><select aria-label="Фильтр по менеджеру" value={owner} onChange={(e) => setOwner(e.target.value)}><option value="">Все менеджеры</option>{state.employees.filter((p) => p.active && p.role !== 'Цех').map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><label className="search-input"><Search size={17} /><input placeholder="Поиск по клиенту или объекту…" value={query} onChange={(e) => setQuery(e.target.value)} aria-label="Поиск заявок" /></label><div className="segmented"><button className={view === 'table' ? 'active' : ''} onClick={() => setView('table')} aria-pressed={view === 'table'}><List size={16} />Таблица</button><button className={view === 'board' ? 'active' : ''} onClick={() => setView('board')} aria-pressed={view === 'board'}><Columns3 size={16} />Доска</button></div></div>
    <div className="sub-toolbar"><select aria-label="Фильтр по этапу" value={stage} onChange={(e) => setStage(e.target.value)}><option value="">Все этапы</option>{LEAD_STAGES.map((s) => <option key={s.id} value={s.id}>{s.label}</option>)}</select><span>{leads.length} заявок</span>{owner || query || stage ? <button className="text-link" onClick={() => { setOwner(''); setQuery(''); setStage(''); }}>Сбросить фильтры</button> : null}</div>
    {view === 'table' ? <div className="table-wrap"><table className="leads-table"><thead><tr><th>Клиент / объект</th><th>Этап</th><th>Следующий шаг</th><th>Ответственный</th><th>Срок</th><th><span className="sr-only">Действия</span></th></tr></thead><tbody>{leads.map((lead) => { const { client, site } = leadContext(state, lead); return <tr key={lead.id} className={selectedId === lead.id ? 'selected' : ''}><td><button className="cell-link" onClick={() => onSelect(lead.id)}><strong>{client.name}</strong><span>{site.name}</span></button></td><td><Badge value={lead.status} stages={LEAD_STAGES} /></td><td className="next-action-cell">{lead.nextAction || 'Не запланирован'}</td><td><span>{employee(lead.ownerId, state)?.name}</span><small>{employee(lead.ownerId, state)?.role}</small></td><td className={isOverdue(lead.dueAt) && lead.status !== 'lost' ? 'amber-text' : 'muted'}>{dateLabel(lead.dueAt)}</td><td><button className="icon-button" aria-label={`Изменить заявку ${client.name}`} onClick={() => onEdit(lead.id)}><MoreHorizontal size={19} /></button></td></tr>; })}</tbody></table>{!leads.length ? <Empty /> : null}</div> : <div className="lead-board">{LEAD_STAGES.filter((s) => !stage || stage === s.id).map((s) => <section key={s.id} className="lead-column"><h3>{s.label}<span>{leads.filter((l) => l.status === s.id).length}</span></h3>{leads.filter((l) => l.status === s.id).map((lead) => { const { client, site } = leadContext(state, lead); return <article className="lead-card" key={lead.id}><button className="cell-link" onClick={() => onSelect(lead.id)}><strong>{client.name}</strong><span>{site.name}</span></button><p>{lead.nextAction}</p><small>{dateLabel(lead.dueAt)}</small><select value={lead.status} aria-label={`Этап ${client.name}`} onChange={(e) => onChangeStage(lead.id, e.target.value)}>{LEAD_STAGES.map((v) => <option key={v.id} value={v.id}>{v.label}</option>)}</select></article>; })}</section>)}</div>}
    <div className="page-footnote">Демонстрационная версия · данные сохраняются в этом браузере</div>
  </section>;
}

export function LeadDetail({ state, lead, onClose, onEdit, onClientEdit, onActivity, onTransfer, onOpenTask, onFull, full = false }) {
  const [tab, setTab] = useState('general');
  const { client, site } = leadContext(state, lead);
  const orders = state.orders.filter((o) => o.siteId === site.id);
  const tasks = state.tasks.filter((t) => orders.some((o) => o.id === t.orderId));
  const events = state.activities.filter((a) => a.siteId === site.id).sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
  return <aside className={`lead-detail ${full ? 'full-detail' : ''}`} aria-label="Карточка заявки"><div className="detail-title"><div><h2>{client.name}</h2><p>{site.name}</p></div>{!full ? <button className="icon-button" onClick={onClose} aria-label="Закрыть карточку"><X size={18} /></button> : null}</div>
    <div className="detail-tabs">{[['general', 'Общее'], ['tasks', `Задачи (${tasks.length})`], ['notes', 'Примечания']].map(([key, label]) => <button key={key} className={tab === key ? 'active' : ''} onClick={() => setTab(key)}>{label}</button>)}</div>
    <div className="detail-scroll">
    {tab === 'general' ? <><dl className="detail-fields"><dt>Статус</dt><dd><Badge value={lead.status} stages={LEAD_STAGES} /></dd><dt>Источник</dt><dd>{lead.source}</dd><dt>Телефон</dt><dd>{client.phone || 'Не указан'}</dd><dt>E-mail</dt><dd>{client.email || 'Не указан'}</dd><dt>Объект</dt><dd>{site.name}</dd><dt>Адрес</dt><dd>{site.address || 'Не указан'}</dd><dt>Менеджер</dt><dd>{employee(lead.ownerId, state)?.name}</dd></dl><button className="text-link" onClick={onClientEdit}><Pencil size={13} />Изменить контакты</button><div className="next-contact"><div className="section-caption"><span><CalendarDays size={19} />Следующий контакт</span><button className="text-link" onClick={onEdit}>Изменить</button></div><strong className={isOverdue(lead.dueAt) ? 'amber-text' : ''}>{dateLabel(lead.dueAt)}</strong><p>{lead.nextAction || 'Запланируйте следующий шаг'}</p></div><div className="section-caption"><h3>История общения</h3><button className="text-link" onClick={onActivity}><Plus size={14} />Добавить</button></div><Timeline state={state} events={events.slice(0, full ? 100 : 5)} compact />{events.length > 5 && !full ? <button className="text-link" onClick={onFull}>Все события ({events.length})</button> : null}</> : null}
    {tab === 'tasks' ? <><div className="section-caption"><h3>Задания по объекту</h3></div>{tasks.length ? tasks.map((task) => <button className="related-task" key={task.id} onClick={() => onOpenTask(task.id)}><strong>{task.title}</strong><span>{employee(task.assigneeId, state)?.name || 'Не назначен'} · {dateLabel(task.dueAt)}</span></button>) : <Empty title="Заданий пока нет">Передайте согласованный заказ в цех.</Empty>}{orders.map((order) => <details className="order-spec" key={order.id}><summary>Комплектация · {order.number}</summary><p>{order.scope}</p><small>{order.reference || 'Спецификация введена вручную'}</small></details>)}</> : null}
    {tab === 'notes' ? <><h3>Примечание к заявке</h3><p className="preserve-lines">{lead.notes || 'Примечаний пока нет'}</p><button className="button" onClick={onEdit}><Pencil size={15} />Редактировать</button><button className="button" onClick={onActivity}><MessageSquare size={15} />Записать общение</button></> : null}
    </div><div className="detail-bottom">{!state.orders.some((o) => o.leadId === lead.id) ? <button className="button primary" onClick={onTransfer}><Factory size={17} />Передать в цех</button> : <p className="success-note">Заказ передан в производство</p>}{!full ? <button className="button" onClick={onFull}>Открыть карточку<ArrowUpRight size={17} /></button> : null}</div>
  </aside>;
}
