import { useState } from 'react';
import { Plus, List, Columns3, Clock3, AlertCircle, CheckSquare, MoreVertical, ArrowRight } from 'lucide-react';
import { Avatar, Badge, Empty, PageHeading, Timeline } from '../components/UI.jsx';
import { TASK_STAGES, dateKey, dateLabel, employee, isOverdue, taskContext } from '../app/model.js';

function TaskCard({ state, task, onOpen }) { const { order, site } = taskContext(state, task); const percent = Math.round(task.completedQty / task.quantity * 100); return <article className={`task-card ${task.status === 'blocked' ? 'blocked-card' : ''}`} draggable onDragStart={(e) => { e.dataTransfer.setData('text/plain', task.id); e.dataTransfer.effectAllowed = 'move'; }}><button className="task-card-title" onClick={() => onOpen(task.id)}><strong>{task.title}</strong><MoreVertical size={16} /></button><p className="task-order">Заказ {order?.number || 'Общая задача'}{site ? ` · ${site.name}` : ''}</p>{task.status === 'blocked' ? <div className="block-reason"><AlertCircle size={16} />{task.blockReason}</div> : task.status === 'review' ? <Badge color="blue">Ожидает приёмки</Badge> : task.status === 'doing' ? <><p className="task-quantity">{task.completedQty} из {task.quantity} {task.unit} готово</p><div className="progress-row"><progress value={percent} max="100" /><span>{percent}%</span></div></> : <p className="task-quantity">{task.quantity} {task.unit}</p>}<div className="task-meta"><span><CheckSquare size={16} />{task.checklist.filter((c) => c.done).length}/{task.checklist.length}</span>{task.priority === 'high' ? <span className="amber-text">Высокий приоритет</span> : null}</div><div className="task-footer"><span><Avatar id={task.assigneeId} state={state} />{employee(task.assigneeId, state)?.name || 'Не назначен'}</span><span className={isOverdue(task.dueAt) ? 'amber-text' : ''}><Clock3 size={14} />{dateLabel(task.dueAt)}</span></div></article>; }
export function Production({ state, search, onCreate, onOpen, onMove, initialOrder = '', mine = false, quick = null }) {
  const [assignee, setAssignee] = useState(''); const [order, setOrder] = useState(initialOrder); const [today, setToday] = useState(false); const [showDone, setShowDone] = useState(false); const [view, setView] = useState(mine ? 'list' : 'board'); const [dragOver, setDragOver] = useState('');
  const tasks = state.tasks.filter((t) => { const ctx = taskContext(state, t); return (!assignee || t.assigneeId === assignee) && (!order || t.orderId === order) && (!today || t.dueAt.slice(0, 10) === dateKey()) && (showDone || t.status !== 'done') && `${t.title} ${ctx.order?.number} ${ctx.site?.name} ${employee(t.assigneeId, state)?.name}`.toLowerCase().includes(search.toLowerCase()); });
  const stages = TASK_STAGES.filter((s) => showDone || s.id !== 'done');
  return <section className="page production-page"><PageHeading title={mine ? 'Мои задачи' : 'Задачи цеха'} description={mine ? 'Выберите сотрудника, чтобы открыть его очередь работ' : 'Работы, исполнители и готовность заказов'}><button className="button primary" onClick={() => onCreate(order)}><Plus size={20} />Новая задача</button></PageHeading>{quick}<div className="toolbar production-toolbar"><button className={`button ${today ? 'tinted' : ''}`} onClick={() => setToday(!today)} aria-pressed={today}>Сегодня</button><span className="date-caption">{new Date().toLocaleDateString('ru-RU', { day: 'numeric', month: 'long' })}</span><select aria-label="Фильтр по сотруднику" value={assignee} onChange={(e) => setAssignee(e.target.value)}><option value="">Все сотрудники</option>{state.employees.filter((p) => p.active && (mine || p.role === 'Цех')).map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</select><select aria-label="Фильтр по заказу" value={order} onChange={(e) => setOrder(e.target.value)}><option value="">Все заказы</option>{state.orders.map((o) => <option key={o.id} value={o.id}>{o.number}</option>)}</select><div className="segmented"><button className={view === 'board' ? 'active' : ''} onClick={() => setView('board')}><Columns3 size={16} />Доска</button><button className={view === 'list' ? 'active' : ''} onClick={() => setView('list')}><List size={16} />Список</button></div></div><div className="sub-toolbar"><label className="inline-check"><input type="checkbox" checked={showDone} onChange={(e) => setShowDone(e.target.checked)} />Показать выполненные</label><span>{tasks.length} заданий</span>{order || assignee || today ? <button className="text-link" onClick={() => { setOrder(''); setAssignee(''); setToday(false); }}>Сбросить фильтры</button> : null}</div>
    {view === 'board' ? <div className={`production-board ${showDone ? 'with-done' : ''}`}>{stages.map((s) => <section key={s.id} className={`production-column ${s.color} ${dragOver === s.id ? 'drag-over' : ''}`} onDragOver={(e) => { e.preventDefault(); setDragOver(s.id); }} onDragLeave={() => setDragOver('')} onDrop={(e) => { e.preventDefault(); setDragOver(''); const id = e.dataTransfer.getData('text/plain'); if (state.tasks.some((t) => t.id === id && t.status !== s.id)) onMove(id, s.id); }}><h2>{s.label}<span>{tasks.filter((t) => t.status === s.id).length}</span></h2>{tasks.filter((t) => t.status === s.id).map((task) => <TaskCard state={state} task={task} key={task.id} onOpen={onOpen} />)}{!tasks.some((t) => t.status === s.id) ? <p className="column-empty">Заданий нет</p> : null}</section>)}</div> : <div className="table-wrap"><table><thead><tr><th>Задание / заказ</th><th>Исполнитель</th><th>Статус</th><th>Срок</th><th>Готовность</th></tr></thead><tbody>{tasks.map((t) => <tr key={t.id}><td><button className="cell-link" onClick={() => onOpen(t.id)}><strong>{t.title}</strong><span>{taskContext(state, t).order?.number}</span></button></td><td>{employee(t.assigneeId, state)?.name || 'Не назначен'}</td><td><Badge stages={TASK_STAGES} value={t.status} /></td><td className={isOverdue(t.dueAt) && t.status !== 'done' ? 'amber-text' : ''}>{dateLabel(t.dueAt)}</td><td>{t.completedQty} / {t.quantity} {t.unit}</td></tr>)}</tbody></table>{!tasks.length ? <Empty /> : null}</div>}
    {!mine ? <section className="workload"><h2>Загрузка на сегодня</h2><div className="table-wrap"><table><thead><tr><th>Сотрудник</th><th>Задач на сегодня</th><th>Состояние работ</th><th>Текущая задача</th></tr></thead><tbody>{state.employees.filter((p) => p.active && (mine || p.role === 'Цех')).map((p) => { const items = state.tasks.filter((t) => t.assigneeId === p.id && t.dueAt.slice(0, 10) === dateKey() && t.status !== 'done'); const active = items.find((t) => t.status === 'doing') || items[0]; return <tr key={p.id}><td><span className="person-cell"><Avatar id={p.id} state={state} />{p.name}</span></td><td>{items.length}</td><td>{items.some((t) => t.status === 'blocked') ? <Badge color="amber">Есть блокировка</Badge> : items.length ? <Badge color="blue">Есть задания</Badge> : <span className="muted">Свободен</span>}</td><td>{active ? <button className="text-link" onClick={() => onOpen(active.id)}>{active.title}<ArrowRight size={14} /></button> : '—'}</td></tr>; })}</tbody></table></div></section> : null}<div className="page-footnote">Перемещайте карточки между колонками или меняйте статус внутри задания.</div>
  </section>;
}
export function TaskDetail({ state, task, onEdit, onCheck, onMove, onComment }) {
  const [check, setCheck] = useState(''); const [comment, setComment] = useState(''); const [error, setError] = useState(''); const { order, site } = taskContext(state, task);
  function submitCheck(e) { e.preventDefault(); if (onCheck({ id: task.id, title: check })) setCheck(''); }
  return <div className="task-detail"><div className="task-detail-summary"><Badge stages={TASK_STAGES} value={task.status} /><span>{order?.number || 'Общая задача'}{site ? ` · ${site.name}` : ''}</span><button className="text-link" onClick={onEdit}>Редактировать</button></div><p className="preserve-lines">{task.description}</p><div className="task-detail-facts"><span><Avatar id={task.assigneeId} state={state} />{employee(task.assigneeId, state)?.name || 'Не назначен'}</span><span><Clock3 size={16} />{dateLabel(task.dueAt)}</span><span>{task.completedQty} / {task.quantity} {task.unit}</span></div>{task.status === 'blocked' ? <div className="block-reason"><AlertCircle size={17} />{task.blockReason}</div> : null}<label className="field"><span>Статус задания</span><select value={task.status} onChange={(e) => onMove(task.id, e.target.value)}>{TASK_STAGES.map((s) => <option key={s.id} value={s.id}>{s.label}</option>)}</select></label><h3>Чек-лист</h3><div className="checklist">{task.checklist.map((item) => <label className="check-row" key={item.id}><input type="checkbox" checked={item.done} disabled={task.status === 'done'} onChange={() => onCheck({ id: task.id, checkId: item.id })} /><span>{item.title}</span></label>)}</div>{task.status !== 'done' ? <form className="inline-form" onSubmit={submitCheck}><input value={check} onChange={(e) => setCheck(e.target.value)} placeholder="Новый пункт чек-листа" aria-label="Новый пункт чек-листа" required maxLength={500} /><button className="button" type="submit"><Plus size={16} />Добавить</button></form> : null}{order ? <details className="order-spec"><summary>Согласованная комплектация · {order?.number}</summary><p>{order?.scope}</p><small>{order?.reference || 'Спецификация введена вручную'}</small></details> : null}<h3>Обсуждение и история</h3><form className="inline-form" onSubmit={(e) => { e.preventDefault(); setError(''); try { onComment({ siteId: site?.id || '', taskId: task.id, type: 'note', text: comment }); setComment(''); } catch (err) { setError(err.message); } }}><input value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Добавить комментарий" aria-label="Комментарий к заданию" required maxLength={5000} /><button className="button" type="submit">Добавить</button></form>{error ? <p className="form-error">{error}</p> : null}<Timeline state={state} events={state.activities.filter((a) => a.taskId === task.id).slice(0, 20)} compact /></div>;
}
