import { useEffect, useRef, useState } from 'react';
import { Mic, Plus, Square } from 'lucide-react';
import { Dialog, Field } from '../components/UI.jsx';
import { EntryForm } from '../components/OperationsUI.jsx';
import { dueAt } from '../app/model.js';

export function QuickTasks({state,command}) {
  const [title,setTitle]=useState('');const [assignee,setAssignee]=useState('');const [due,setDue]=useState(dueAt(0));const [order,setOrder]=useState('');const [notice,setNotice]=useState('');const [templateModal,setTemplateModal]=useState(false);const [listening,setListening]=useState(false);const recognition=useRef(null);
  useEffect(()=>()=>recognition.current?.abort(),[]);
  const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;
  function record(){if(listening){recognition.current?.stop();return;}if(!Speech)return;const r=new Speech();recognition.current=r;r.lang='ru-RU';r.continuous=false;r.interimResults=false;r.onresult=(e)=>{setTitle(e.results[0][0].transcript);setNotice('Текст распознан. Проверьте задачу, сотрудника и срок перед добавлением.');};r.onend=()=>setListening(false);r.onerror=()=>{setListening(false);setNotice('Распознавание не удалось. Проверьте разрешение микрофона или введите текст.');};try{r.start();setListening(true);}catch{setNotice('Не удалось включить микрофон.');}}
  const template=state.taskTemplates.find((t)=>t.title===title);
  function submit(e){e.preventDefault();try{command('task.create',{title,description:template?.description||'',templateId:template?.id||'',orderId:order,assigneeId:assignee,dueAt:due,quantity:1,completedQty:0,unit:template?.unit||'задача',priority:'normal',status:'planned'});setTitle('');setNotice('Задача добавлена. Сотрудник и срок сохранены для следующего задания.');}catch(err){setNotice(err.message);}}
  return <section className="quick-task"><div className="section-caption"><h2>Быстрая задача</h2><button className="text-link" onClick={()=>setTemplateModal(true)}>Повторяющиеся действия</button></div><form onSubmit={submit}><Field label="Задача или действие из списка"><input list="task-actions" required maxLength={200} value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="Начните вводить действие…"/><datalist id="task-actions">{state.taskTemplates.filter((t)=>t.active).map((t)=><option value={t.title} key={t.id}/>)}</datalist></Field><Field label="Сотрудник"><select required value={assignee} onChange={(e)=>setAssignee(e.target.value)}><option value="">Выберите сотрудника</option>{state.employees.filter((p)=>p.active).map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Дата и время"><input type="datetime-local" required value={due} onChange={(e)=>setDue(e.target.value)}/></Field><Field label="Заказ"><select value={order} onChange={(e)=>setOrder(e.target.value)}><option value="">Без заказа</option>{state.orders.map((o)=><option key={o.id} value={o.id}>{o.number}</option>)}</select></Field><button className="button primary" type="submit"><Plus size={16}/>Добавить</button><button className="button" type="button" disabled={!Speech} onClick={record}>{listening?<Square size={16}/>:<Mic size={16}/>} {listening?'Остановить':'Голос'}</button></form><p className="ops-hint">{Speech?'Голос заполняет текст задачи. Сотрудника и срок выберите в форме. Распознавание может отправлять аудио в сервис вашего браузера.':'Голосовой ввод не поддерживается этим браузером. Можно использовать диктовку клавиатуры устройства.'}</p>{notice?<p role="status" className="inline-notice">{notice}</p>:null}{templateModal?<Dialog title="Повторяющиеся действия" onClose={()=>setTemplateModal(false)}><TemplateEditor state={state} command={command} onClose={()=>setTemplateModal(false)}/></Dialog>:null}</section>;
}
function TemplateEditor({state,command,onClose}) {
  const [id,setId]=useState('');const template=state.taskTemplates.find((t)=>t.id===id);
  return <><div className="form-content"><Field label="Выберите действие для изменения"><select value={id} onChange={(e)=>setId(e.target.value)}><option value="">Новое действие</option>{state.taskTemplates.map((t)=><option key={t.id} value={t.id}>{t.title}{t.active?'':' · архив'}</option>)}</select></Field></div><EntryForm key={id} onClose={onClose} onSubmit={(p)=>{command('template.save',{...p,id,active:p.active==='on'});onClose();}}><Field label="Название действия *" wide><input name="title" required defaultValue={template?.title}/></Field><Field label="Единица"><input name="unit" required defaultValue={template?.unit||'задача'}/></Field><Field label="Описание" wide><textarea name="description" defaultValue={template?.description}/></Field><Field label="Чек-лист: один пункт на строку" wide><textarea name="checklist" rows={4} defaultValue={template?.checklist.join('\n')}/></Field><label className="check-row field-wide"><input name="active" type="checkbox" defaultChecked={template?.active!==false}/>Доступно для новых задач</label><p className="form-hint field-wide">Изменение шаблона применяется к новым задачам. Существующие задания сохраняют свой чек-лист.</p></EntryForm></>;
}
