import { useState } from 'react';
import { Plus, ArrowUpRight, ChevronLeft, ChevronRight, Phone, Factory, AlertCircle, CalendarDays, MessageSquare, Mail, Send, Search, CheckCheck, Settings2 } from 'lucide-react';
import { Badge, Empty, PageHeading, Timeline, VoiceInput } from '../components/UI.jsx';
import { ACTIVITY_TYPES, LEAD_STAGES, TASK_STAGES, dateKey, dateLabel, employee, isOverdue, leadContext, taskContext } from '../app/model.js';

export function Overview({ state, navigate, onLead, onTask }) {
  const lateLeads = state.leads.filter((l) => l.status !== 'lost' && isOverdue(l.dueAt));
  const blocked = state.tasks.filter((t) => t.status === 'blocked'); const review = state.tasks.filter((t) => t.status === 'review');
  const tiles = [{ label: 'Заявки в работе', count: state.leads.filter((l) => l.status !== 'lost').length, icon: Phone, target: 'leads' }, { label: 'Активные задания', count: state.tasks.filter((t) => t.status !== 'done').length, icon: Factory, target: 'production' }, { label: 'Требуют внимания', count: lateLeads.length + blocked.length, icon: AlertCircle, target: 'calendar' }];
  return <section className="page"><PageHeading title="Обзор" description="Заявки, производство и ближайшие действия" /><div className="overview-metrics">{tiles.map(({ label, count, icon: Icon, target }) => <button key={label} onClick={() => navigate(target)}><Icon size={22} /><strong>{count}</strong><span>{label}</span><ArrowUpRight size={17} /></button>)}</div><div className="overview-columns"><section className="section-panel"><h2>Связаться с клиентами</h2>{lateLeads.length ? lateLeads.map((l) => <button className="action-row" key={l.id} onClick={() => onLead(l.id)}><Phone size={18} /><div><strong>{leadContext(state, l).client.name}</strong><span>{l.nextAction}</span></div><small className="amber-text">{dateLabel(l.dueAt)}</small></button>) : <Empty title="Просроченных контактов нет">Следующие встречи и звонки — в календаре.</Empty>}</section><section className="section-panel"><h2>Внимание производству</h2>{[...blocked, ...review].map((t) => <button className="action-row" key={t.id} onClick={() => onTask(t.id)}><Factory size={18} /><div><strong>{t.title}</strong><span>{t.blockReason || 'Результат ожидает приёмки'}</span></div><Badge value={t.status} stages={TASK_STAGES} /></button>)}{!blocked.length && !review.length ? <Empty title="Нет заданий на проверке" /> : null}</section></div><section className="section-panel"><div className="section-caption"><h2>Последние события</h2><button className="text-link" onClick={() => navigate('communications')}>Вся история<ArrowUpRight size={15} /></button></div><Timeline state={state} events={state.activities.slice(0, 6)} compact /></section></section>;
}
export function Clients({ state, search, onLead, onSite, onCreate }) { const clients = state.clients.filter((c) => `${c.name} ${c.phone} ${c.email}`.toLowerCase().includes(search.toLowerCase())); return <section className="page"><PageHeading title="Клиенты и объекты" description="Контакты, объекты строительства и связанные заявки"><button className="button primary" onClick={onCreate}><Plus size={18} />Новый клиент</button></PageHeading><div className="table-wrap"><table><thead><tr><th>Клиент</th><th>Телефон / почта</th><th>Объекты</th><th>Заявки</th></tr></thead><tbody>{clients.map((c) => { const sites = state.sites.filter((s) => s.clientId === c.id); const leads = state.leads.filter((l) => sites.some((s) => s.id === l.siteId)); const primaryLead = leads[0]; return <tr key={c.id}><td>{primaryLead ? <button className="cell-link" onClick={() => onLead(primaryLead.id)}><strong>{c.name}</strong><span>Открыть карточку клиента</span></button> : <strong>{c.name}</strong>}</td><td>{c.phone || 'Телефон не указан'}<small>{c.email || 'Почта не указана'}</small></td><td>{sites.map((s) => <button className="cell-link" key={s.id} onClick={() => onSite(s.id)}><strong>{s.name}</strong><span>{s.address || 'Открыть строительство'}</span></button>)}</td><td>{leads.map((l) => <button key={l.id} className="client-lead-link" onClick={() => onLead(l.id)}><Badge value={l.status} stages={LEAD_STAGES} /><ArrowUpRight size={15} /></button>)}</td></tr>; })}</tbody></table>{!clients.length ? <Empty /> : null}</div></section>; }
const CHANNELS = [
  { id: '', label: 'Все каналы', icon: MessageSquare }, { id: 'email', label: 'Почта Mail.ru', icon: Mail },
  { id: 'whatsapp', label: 'WhatsApp', icon: MessageSquare }, { id: 'telegram', label: 'Telegram', icon: Send },
  { id: 'max', label: 'MAX', icon: MessageSquare }, { id: 'note', label: 'Внутренние', icon: Phone },
];
const channelName = (id) => CHANNELS.find((item) => item.id === id)?.label || (id === 'call' ? 'Звонок' : 'Система');

export function Communications({ state, search, command, notify, onCreate, onLead }) {
  const [channel, setChannel] = useState(''); const [selectedSite, setSelectedSite] = useState(''); const [onlyUnread, setOnlyUnread] = useState(false); const [message, setMessage] = useState(''); const [subject, setSubject] = useState(''); const [settingsOpen, setSettingsOpen] = useState(false);
  const available = state.activities.filter((a) => !['system'].includes(a.channel) && (!channel || a.channel === channel) && (!onlyUnread || !a.read));
  const conversations = state.sites.map((site) => {
    const client = state.clients.find((item) => item.id === site.clientId); const items = available.filter((item) => item.siteId === site.id).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));
    const all = state.activities.filter((item) => item.siteId === site.id && (!channel || item.channel === channel));
    return { site, client, items, last: items[0], unread: all.filter((item)=>!item.read).length };
  }).filter((row) => row.last && `${row.client?.name} ${row.site.name} ${row.last.text}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>new Date(b.last.createdAt)-new Date(a.last.createdAt));
  const activeId = selectedSite && conversations.some((row)=>row.site.id===selectedSite) ? selectedSite : conversations[0]?.site.id || '';
  const active = state.sites.find((item)=>item.id===activeId); const client = state.clients.find((item)=>item.id===active?.clientId); const lead = state.leads.find((item)=>item.siteId===activeId);
  const thread = state.activities.filter((item)=>item.siteId===activeId && (!channel || item.channel===channel) && item.channel !== 'system').sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt));
  const send = async (event) => { event.preventDefault(); try { await command('communication.send',{siteId:activeId,channel:channel || 'telegram',subject,text:message}); setMessage(''); setSubject(''); notify('Сообщение сохранено в переписке'); } catch(error) { notify(error.message,true); } };
  const selectConversation = async (id) => { setSelectedSite(id); try { await command('communication.read',{siteId:id,channel}); } catch(error) { notify(error.message,true); } };
  const unreadTotal = state.activities.filter((item)=>!item.read).length;
  return <section className="page communications-page">
    <PageHeading title="Центр общения" description="Клиенты, объекты и все каналы в одном окне"><div className="communication-heading-actions"><button className="button" onClick={()=>setSettingsOpen((value)=>!value)}><Settings2 size={17}/>Подключения</button><button className="button primary" onClick={()=>onCreate(activeId)}><Plus size={18}/>Записать звонок</button></div></PageHeading>
    {settingsOpen ? <section className="connector-panel"><div><strong>Подключения каналов</strong><span>Сообщения уже имеют единый формат. Токены и пароли будут храниться только на сервере.</span></div>{['Почта Mail.ru','Telegram','WhatsApp','MAX','VK WorkSpace'].map((name,index)=><article key={name}><span className={`connector-mark ${index < 2 ? 'ready' : ''}`}/><div><strong>{name}</strong><small>{index < 2 ? 'Готово к настройке' : 'Подготовлено в модели CRM'}</small></div></article>)}</section> : null}
    <div className="communication-workspace">
      <aside className="channel-rail"><strong>Каналы</strong>{CHANNELS.map(({id,label,icon:Icon})=>{const count=state.activities.filter((item)=>(!id||item.channel===id)&&!item.read).length;return <button key={id||'all'} className={channel===id?'active':''} onClick={()=>{setChannel(id);setSelectedSite('');}}><Icon size={17}/><span>{label}</span>{count?<b>{count}</b>:null}</button>;})}<button className={`unread-filter ${onlyUnread?'active':''}`} onClick={()=>setOnlyUnread((value)=>!value)}><CheckCheck size={17}/><span>Непрочитанные</span>{unreadTotal?<b>{unreadTotal}</b>:null}</button></aside>
      <section className="conversation-column"><div className="conversation-search"><Search size={16}/><span>{onlyUnread?'Непрочитанные диалоги':'Последние диалоги'}</span></div>{conversations.map((row)=><button key={row.site.id} className={`conversation-card ${activeId===row.site.id?'active':''}`} onClick={()=>selectConversation(row.site.id)}><span className="conversation-avatar">{row.client?.name?.split(' ').map((part)=>part[0]).slice(0,2).join('')}</span><span className="conversation-copy"><strong>{row.client?.name}</strong><small>{row.site.name} · {channelName(row.last.channel)}</small><span>{row.last.text}</span></span><span className="conversation-meta"><time>{dateLabel(row.last.createdAt)}</time>{row.unread?<b>{row.unread}</b>:null}</span></button>)}{!conversations.length?<Empty title="Диалогов нет">Измените фильтр или запишите общение.</Empty>:null}</section>
      <section className="thread-column">{active ? <><header className="thread-header"><div><strong>{client?.name}</strong><span>{active.name} · {active.address}</span></div>{lead?<button className="text-link" onClick={()=>onLead(lead.id)}>Открыть карточку<ArrowUpRight size={14}/></button>:null}</header><div className="message-thread">{thread.map((item)=><article key={item.id} className={`message-bubble ${item.direction}`}><small>{channelName(item.channel)}{item.subject?` · ${item.subject}`:''}</small><p>{item.text}</p><footer><span>{item.direction==='incoming'?(client?.name||'Клиент'):(employee(item.authorId,state)?.name||'ЭФТ')}</span><time>{dateLabel(item.createdAt)}</time></footer></article>)}{!thread.length?<Empty title="В этом канале сообщений нет">Напишите первое сообщение ниже.</Empty>:null}</div><form className="message-composer" onSubmit={send}>{(channel||'telegram')==='email'?<input value={subject} onChange={(event)=>setSubject(event.target.value)} placeholder="Тема письма" maxLength={500}/>:null}<div><select aria-label="Канал отправки" value={channel||'telegram'} onChange={(event)=>setChannel(event.target.value)}><option value="email">Mail.ru</option><option value="telegram">Telegram</option><option value="whatsapp">WhatsApp</option><option value="max">MAX</option><option value="note">Внутренняя заметка</option><option value="call">Итог звонка</option></select><VoiceInput><textarea aria-label="Новое сообщение" value={message} onChange={(event)=>setMessage(event.target.value)} placeholder="Введите сообщение или нажмите микрофон…" rows={2} maxLength={20000} required/></VoiceInput><button className="button primary" aria-label="Отправить"><Send size={18}/></button></div><small>До подключения внешнего канала запись сохраняется в CRM и не отправляется адресату.</small></form></> : <Empty title="Выберите диалог"/>}</section>
    </div>
  </section>;
}
