import { useState } from 'react';
import { Plus, ArrowUpRight, ChevronLeft, ChevronRight, Phone, Factory, AlertCircle, CalendarDays, MessageSquare } from 'lucide-react';
import { Badge, Empty, PageHeading, Timeline } from '../components/UI.jsx';
import { ACTIVITY_TYPES, EMPLOYEES, LEAD_STAGES, TASK_STAGES, dateKey, dateLabel, employee, isOverdue, leadContext, taskContext } from '../app/model.js';

export function Overview({ state, navigate, onLead, onTask }) {
  const lateLeads = state.leads.filter((l) => l.status !== 'lost' && isOverdue(l.dueAt));
  const blocked = state.tasks.filter((t) => t.status === 'blocked'); const review = state.tasks.filter((t) => t.status === 'review');
  const tiles = [{ label: 'Заявки в работе', count: state.leads.filter((l) => l.status !== 'lost').length, icon: Phone, target: 'leads' }, { label: 'Активные задания', count: state.tasks.filter((t) => t.status !== 'done').length, icon: Factory, target: 'production' }, { label: 'Требуют внимания', count: lateLeads.length + blocked.length, icon: AlertCircle, target: 'calendar' }];
  return <section className="page"><PageHeading title="Обзор" description="Заявки, производство и ближайшие действия" /><div className="overview-metrics">{tiles.map(({ label, count, icon: Icon, target }) => <button key={label} onClick={() => navigate(target)}><Icon size={22} /><strong>{count}</strong><span>{label}</span><ArrowUpRight size={17} /></button>)}</div><div className="overview-columns"><section className="section-panel"><h2>Связаться с клиентами</h2>{lateLeads.length ? lateLeads.map((l) => <button className="action-row" key={l.id} onClick={() => onLead(l.id)}><Phone size={18} /><div><strong>{leadContext(state, l).client.name}</strong><span>{l.nextAction}</span></div><small className="amber-text">{dateLabel(l.dueAt)}</small></button>) : <Empty title="Просроченных контактов нет">Следующие встречи и звонки — в календаре.</Empty>}</section><section className="section-panel"><h2>Внимание производству</h2>{[...blocked, ...review].map((t) => <button className="action-row" key={t.id} onClick={() => onTask(t.id)}><Factory size={18} /><div><strong>{t.title}</strong><span>{t.blockReason || 'Результат ожидает приёмки'}</span></div><Badge value={t.status} stages={TASK_STAGES} /></button>)}{!blocked.length && !review.length ? <Empty title="Нет заданий на проверке" /> : null}</section></div><section className="section-panel"><div className="section-caption"><h2>Последние события</h2><button className="text-link" onClick={() => navigate('communications')}>Вся история<ArrowUpRight size={15} /></button></div><Timeline events={state.activities.slice(0, 6)} compact /></section></section>;
}
export function Clients({ state, search, onLead, onCreate }) { const clients = state.clients.filter((c) => `${c.name} ${c.phone} ${c.email}`.toLowerCase().includes(search.toLowerCase())); return <section className="page"><PageHeading title="Клиенты и объекты" description="Контакты, объекты строительства и связанные заявки"><button className="button primary" onClick={onCreate}><Plus size={18} />Новый клиент</button></PageHeading><div className="table-wrap"><table><thead><tr><th>Клиент</th><th>Телефон / почта</th><th>Объекты</th><th>Заявки</th></tr></thead><tbody>{clients.map((c) => { const sites = state.sites.filter((s) => s.clientId === c.id); const leads = state.leads.filter((l) => sites.some((s) => s.id === l.siteId)); return <tr key={c.id}><td><strong>{c.name}</strong></td><td>{c.phone || 'Телефон не указан'}<small>{c.email || 'Почта не указана'}</small></td><td>{sites.map((s) => <div key={s.id}>{s.name}<small>{s.address}</small></div>)}</td><td>{leads.map((l) => <button key={l.id} className="client-lead-link" onClick={() => onLead(l.id)}><Badge value={l.status} stages={LEAD_STAGES} /><ArrowUpRight size={15} /></button>)}</td></tr>; })}</tbody></table>{!clients.length ? <Empty /> : null}</div></section>; }
export function Communications({ state, search, onCreate, onLead }) { const [siteId, setSiteId] = useState(''); const [type, setType] = useState(''); const events = state.activities.filter((a) => (!siteId || a.siteId === siteId) && (!type || a.type === type) && `${a.text} ${state.sites.find((s) => s.id === a.siteId)?.name}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)); return <section className="page communications-page"><PageHeading title="Общение" description="История звонков, встреч и договорённостей по объектам"><button className="button primary" onClick={() => onCreate(siteId)}><Plus size={18} />Записать общение</button></PageHeading><div className="integration-note"><MessageSquare size={21} /><p>Пока здесь ручные записи и события системы. Почту и мессенджеры подключим отдельным этапом.</p></div><div className="toolbar"><select aria-label="Объект в истории" value={siteId} onChange={(e) => setSiteId(e.target.value)}><option value="">Все объекты</option>{state.sites.map((s) => <option value={s.id} key={s.id}>{state.clients.find((c) => c.id === s.clientId)?.name} · {s.name}</option>)}</select><select aria-label="Тип события" value={type} onChange={(e) => setType(e.target.value)}><option value="">Все события</option>{Object.entries(ACTIVITY_TYPES).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></div><section className="communication-list">{events.map((a) => { const site = state.sites.find((s) => s.id === a.siteId); const lead = state.leads.find((l) => l.siteId === a.siteId); return <article key={a.id}><span className="message-icon"><MessageSquare size={18} /></span><div><div className="section-caption"><strong>{ACTIVITY_TYPES[a.type]}</strong><time>{dateLabel(a.createdAt)}</time></div><p className="preserve-lines">{a.text}</p><button className="text-link" onClick={() => onLead(lead?.id)}>{state.clients.find((c) => c.id === site?.clientId)?.name} · {site?.name}<ArrowUpRight size={14} /></button><small>{employee(a.authorId)?.name}</small></div></article>; })}{!events.length ? <Empty title="Событий пока нет">Добавьте запись об общении с клиентом.</Empty> : null}</section></section>; }
export function Calendar({ state, search, onLead, onTask }) {
  const [offset, setOffset] = useState(0); const [owner, setOwner] = useState('');
  const start = new Date(); start.setHours(12, 0, 0, 0); start.setDate(start.getDate() - (start.getDay() + 6) % 7 + offset * 7);
  const days = Array.from({ length: 7 }, (_, i) => { const d = new Date(start); d.setDate(d.getDate() + i); return d; });
  const events = [...state.leads.filter((l) => l.dueAt && l.status !== 'lost').map((l) => ({ id: l.id, kind: 'lead', title: l.nextAction, label: leadContext(state, l).client.name, date: l.dueAt, owner: l.ownerId })), ...state.tasks.filter((t) => t.dueAt && t.status !== 'done').map((t) => ({ id: t.id, kind: 'task', title: t.title, label: taskContext(state, t).order?.number, date: t.dueAt, owner: t.assigneeId }))].filter((e) => (!owner || e.owner === owner) && `${e.title} ${e.label}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => a.date.localeCompare(b.date));
  return <section className="page"><PageHeading title="Календарь" description="Контакты с клиентами и сроки производственных заданий" /><div className="toolbar"><button className="icon-button bordered" aria-label="Предыдущая неделя" onClick={() => setOffset(offset - 1)}><ChevronLeft size={18} /></button><button className="button" onClick={() => setOffset(0)}>Сегодня</button><button className="icon-button bordered" aria-label="Следующая неделя" onClick={() => setOffset(offset + 1)}><ChevronRight size={18} /></button><strong>{dateLabel(dateKey(days[0]), false)} — {dateLabel(dateKey(days[6]), false)}</strong><select aria-label="Сотрудник в календаре" value={owner} onChange={(e) => setOwner(e.target.value)}><option value="">Все сотрудники</option>{EMPLOYEES.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="calendar-grid">{days.map((day) => <section key={dateKey(day)} className={`calendar-day ${dateKey(day) === dateKey() ? 'today' : ''}`}><header><span>{day.toLocaleDateString('ru-RU', { weekday: 'short' })}</span><strong>{day.getDate()}</strong></header>{events.filter((e) => e.date.slice(0, 10) === dateKey(day)).map((event) => <button key={`${event.kind}-${event.id}`} className={`calendar-event ${event.kind}`} onClick={() => event.kind === 'lead' ? onLead(event.id) : onTask(event.id)}><span>{event.date.slice(11, 16)} · {event.kind === 'lead' ? 'Контакт' : 'Цех'}</span><strong>{event.title}</strong><small>{event.label}</small><small>{employee(event.owner)?.name || 'Не назначен'}</small></button>)}{!events.some((e) => e.date.slice(0, 10) === dateKey(day)) ? <p className="column-empty">Нет событий</p> : null}</section>)}</div></section>;
}
