import { useEffect, useState } from 'react';
import { Bell, Search, ChevronDown, Home, ClipboardList, Users, MessageSquare, Factory, CheckSquare, CalendarDays, Package, HardHat, Truck, Database, Menu, X, LayoutDashboard, CircleCheck, AlertCircle } from 'lucide-react';
import { useWorkspace } from './useWorkspace.js';
import { employee, isOverdue, leadContext } from './model.js';
import { Dialog } from '../components/UI.jsx';
import { ActivityForm, ClientForm, DataTools, LeadForm, OrderForm, TaskForm } from '../components/Forms.jsx';
import { Leads, LeadDetail } from '../features/Leads.jsx';
import { Production, TaskDetail } from '../features/Production.jsx';
import { Calendar, Clients, Communications, Overview } from '../features/WorkspacePages.jsx';
import './app.css';

const navigation = [
  { id: 'overview', label: 'Обзор', icon: Home }, { id: 'leads', label: 'Заявки', icon: ClipboardList }, { id: 'clients', label: 'Клиенты и объекты', icon: Users }, { id: 'communications', label: 'Общение', icon: MessageSquare },
  { id: 'production', label: 'Производство', icon: Factory, separator: true }, { id: 'tasks', label: 'Мои задачи', icon: CheckSquare }, { id: 'calendar', label: 'Календарь', icon: CalendarDays },
  { id: 'supplies', label: 'Закупки и склад', icon: Package, separator: true, planned: true }, { id: 'crews', label: 'Бригады', icon: HardHat, planned: true }, { id: 'logistics', label: 'Логистика', icon: Truck, planned: true },
];
const getPage = () => { const id = window.location.hash.slice(1); return navigation.some((v) => v.id === id && !v.planned) ? id : 'leads'; };
export function App() {
  const { state, command, storageError, replace } = useWorkspace();
  const [page, setPage] = useState(getPage); const [search, setSearch] = useState(''); const [selectedLead, setSelectedLead] = useState(() => window.innerWidth > 1050 ? 'lead-3' : ''); const [modal, setModal] = useState(null); const [toast, setToast] = useState(null); const [sidebar, setSidebar] = useState(false);
  const selected = state.leads.find((l) => l.id === selectedLead);
  const late = state.leads.filter((l) => l.status !== 'lost' && isOverdue(l.dueAt)); const blocked = state.tasks.filter((t) => t.status === 'blocked');
  useEffect(() => { const change = () => { setPage(getPage()); setSearch(''); }; window.addEventListener('hashchange', change); return () => window.removeEventListener('hashchange', change); }, []);
  useEffect(() => { if (!toast) return; const id = setTimeout(() => setToast(null), 4500); return () => clearTimeout(id); }, [toast]);
  function navigate(id) { const item = navigation.find((v) => v.id === id); if (item?.planned) { setModal({ type: 'planned', id }); return; } setPage(id); setSearch(''); setSidebar(false); window.location.hash = id; }
  function mutate(action, payload, message = 'Сохранено') { const next = command(action, payload); setToast({ text: message, error: false }); return next; }
  function safeMutate(action, payload, message) { try { mutate(action, payload, message); return true; } catch (e) { setToast({ text: e.message, error: true }); return false; } }
  function openLead(id) { if (!id) return; setSelectedLead(id); navigate('leads'); }
  function moveTask(id, status) { if (status === 'blocked') setModal({ type: 'task-edit', id, status }); else safeMutate('task.update', { id, status }, 'Статус задания обновлён'); }
  function detailProps(lead, full = false) { return { state, lead, full, onClose: () => setSelectedLead(''), onEdit: () => setModal({ type: 'lead-edit', id: lead.id }), onClientEdit: () => setModal({ type: 'client-edit', id: lead.id }), onActivity: () => setModal({ type: 'activity', siteId: lead.siteId }), onTransfer: () => setModal({ type: 'order', id: lead.id }), onOpenTask: (id) => setModal({ type: 'task', id }), onFull: () => setModal({ type: 'lead-full', id: lead.id }) }; }
  const closeModal = () => setModal(null);
  const modalLead = state.leads.find((l) => l.id === modal?.id); const modalTask = state.tasks.find((t) => t.id === modal?.id);
  let dialog = null;
  if (modal?.type === 'lead-new' || (modal?.type === 'lead-edit' && modalLead)) dialog = <Dialog key={`${modal.type}-${modal.id}`} title={modal.type === 'lead-new' ? 'Новая заявка' : 'Изменить заявку'} onClose={closeModal}><LeadForm state={state} lead={modalLead} onClose={closeModal} onSubmit={(p) => { const next = mutate(modal.type === 'lead-new' ? 'lead.create' : 'lead.update', { ...p, id: modal?.id }, modal.type === 'lead-new' ? 'Заявка создана' : 'Заявка обновлена'); if (modal.type === 'lead-new') openLead(next.leads[0].id); closeModal(); }} /></Dialog>;
  if (modal?.type === 'client-edit' && modalLead) { const { client, site } = leadContext(state, modalLead); dialog = <Dialog title="Контакты и объект" onClose={closeModal}><ClientForm client={client} site={site} onClose={closeModal} onSubmit={(p) => { mutate('client.update', { ...p, id: client.id, siteId: site.id }); closeModal(); }} /></Dialog>; }
  if (modal?.type === 'activity') dialog = <Dialog title="Записать общение" onClose={closeModal}><ActivityForm state={state} siteId={modal.siteId} onClose={closeModal} onSubmit={(p) => { mutate('activity.create', p, 'Запись добавлена в историю'); closeModal(); }} /></Dialog>;
  if (modal?.type === 'order' && modalLead) dialog = <Dialog title="Передать заказ в производство" onClose={closeModal}><OrderForm onClose={closeModal} onSubmit={(p) => { mutate('order.create', { ...p, leadId: modal.id }, 'Созданы заказ и первое задание цеху'); closeModal(); }} /></Dialog>;
  if (modal?.type === 'task-new' || (modal?.type === 'task-edit' && modalTask)) dialog = <Dialog key={`${modal.type}-${modal.id}`} title={modal.type === 'task-new' ? 'Новое задание' : 'Изменить задание'} onClose={closeModal}><TaskForm state={state} task={modalTask ? { ...modalTask, status: modal.status || modalTask.status } : null} orderId={modal.orderId} onClose={closeModal} onSubmit={(p) => { const next = mutate(modal.type === 'task-new' ? 'task.create' : 'task.update', { ...p, id: modal.id }, 'Задание сохранено'); setModal({ type: 'task', id: modal.type === 'task-new' ? next.tasks[0].id : modal.id }); }} /></Dialog>;
  if (modal?.type === 'task' && modalTask) dialog = <Dialog title={modalTask.title} onClose={closeModal} wide><TaskDetail state={state} task={modalTask} onEdit={() => setModal({ type: 'task-edit', id: modalTask.id })} onCheck={(p) => safeMutate('task.check', p, 'Чек-лист обновлён')} onMove={moveTask} onComment={(p) => mutate('activity.create', p, 'Комментарий добавлен')} /></Dialog>;
  if (modal?.type === 'lead-full' && modalLead) dialog = <Dialog title="Карточка клиента и объекта" onClose={closeModal} wide><LeadDetail key={modalLead.id} {...detailProps(modalLead, true)} /></Dialog>;
  if (modal?.type === 'data') dialog = <Dialog title="Данные на этом устройстве" onClose={closeModal}><DataTools state={state} replace={replace} onClose={closeModal} /></Dialog>;
  if (modal?.type === 'notifications') dialog = <Dialog title="Требуют внимания" onClose={closeModal}><div className="form-content">{!late.length && !blocked.length ? <p>Просроченных контактов и блокировок нет.</p> : null}{late.map((l) => <button className="action-row" key={l.id} onClick={() => { openLead(l.id); closeModal(); }}><CalendarDays size={18} /><div><strong>{leadContext(state, l).client.name}</strong><span>{l.nextAction}</span></div></button>)}{blocked.map((t) => <button className="action-row" key={t.id} onClick={() => setModal({ type: 'task', id: t.id })}><AlertCircle size={18} /><div><strong>{t.title}</strong><span>{t.blockReason}</span></div></button>)}</div></Dialog>;
  if (modal?.type === 'planned') dialog = <Dialog title={navigation.find((n) => n.id === modal.id)?.label} onClose={closeModal}><div className="form-content"><p className="data-explanation">Этот раздел входит в следующие этапы разработки.</p><p>{modal.id === 'supplies' ? 'Потребности по объектам, заказы поставщикам, приёмка, резервы, выдача материалов и учёт инструмента.' : modal.id === 'crews' ? 'Состав бригад, специализации, назначение на строительные этапы и проверка занятости.' : 'Комплектация, рейсы, окна доставки и подтверждение приёмки на объекте.'}</p><p className="muted small">Сейчас доступны заявки, клиенты, история общения, цех, задачи и календарь.</p></div><footer className="dialog-actions"><button className="button primary" onClick={closeModal}>Понятно</button></footer></Dialog>;
  const taskProps = { state, search, onCreate: (orderId) => setModal({ type: 'task-new', orderId }), onOpen: (id) => setModal({ type: 'task', id }), onMove: moveTask };
  return <div className="app-shell">
    {sidebar ? <button className="sidebar-backdrop" aria-label="Закрыть меню" onClick={() => setSidebar(false)} /> : null}
    <aside className={`sidebar ${sidebar ? 'is-open' : ''}`}><a href="#overview" className="brand" onClick={() => navigate('overview')}><strong>ЭФТ</strong><span>Управление<br />строительством</span></a><nav aria-label="Основная навигация">{navigation.map(({ id, icon: Icon, label, separator, planned }) => <div className={separator ? 'nav-group-start' : ''} key={id}><button className={`nav-item ${page === id ? 'active' : ''} ${planned ? 'planned' : ''}`} aria-current={page === id ? 'page' : undefined} onClick={() => navigate(id)}><Icon size={20} /><span>{label}</span>{planned ? <span className="planned-dot" title="Следующий этап" /> : null}</button></div>)}</nav><div className="sidebar-bottom"><button onClick={() => setModal({ type: 'data' })}><Database size={17} /><span>Данные и резервная копия</span></button><span className="demo-label"><span />Демо · на этом устройстве</span><small>ЭФТ CRM · {__BUILD_REVISION__}</small></div></aside>
    <div className="workspace"><header className="topbar"><button className="icon-button mobile-menu" aria-label="Открыть меню" onClick={() => setSidebar(true)}><Menu size={22} /></button><label className="workspace-select"><LayoutDashboard size={17} /><select aria-label="Рабочее пространство" value={['production', 'tasks'].includes(page) ? 'factory' : 'office'} onChange={(e) => navigate(e.target.value === 'factory' ? 'production' : 'leads')}><option value="office">Офис</option><option value="factory">Цех</option></select></label><label className="global-search"><Search size={19} /><input aria-label="Общий поиск" placeholder="Поиск по клиентам, объектам, задачам…" value={search} onChange={(e) => { setSearch(e.target.value); if (page === 'overview') { setPage('leads'); window.history.replaceState(null, '', '#leads'); } }} />{search ? <button className="icon-button" aria-label="Очистить поиск" onClick={() => setSearch('')}><X size={14} /></button> : null}</label><button className="notification-button icon-button" aria-label={`Требуют внимания: ${late.length + blocked.length}`} onClick={() => setModal({ type: 'notifications' })}><Bell size={21} />{late.length + blocked.length ? <i /> : null}</button><button className="profile-button" onClick={() => setModal({ type: 'data' })}><span className="profile-avatar">ЭФ</span><span>Рабочее пространство<small>Ознакомительная версия</small></span><ChevronDown size={15} /></button></header>
    {storageError ? <div className="storage-error" role="alert">{storageError}<button onClick={() => setModal({ type: 'data' })}>Открыть данные</button></div> : null}
    <main className={`workspace-body ${page === 'leads' && selected ? 'with-detail' : ''}`}>
      {page === 'leads' ? <><Leads state={state} search={search} selectedId={selectedLead} onSelect={setSelectedLead} onCreate={() => setModal({ type: 'lead-new' })} onEdit={(id) => setModal({ type: 'lead-edit', id })} onChangeStage={(id, status) => safeMutate('lead.update', { id, status }, 'Этап обновлён')} />{selected ? <LeadDetail key={selected.id} {...detailProps(selected)} /> : null}</> : null}
      {page === 'production' || page === 'tasks' ? <Production key={page} {...taskProps} mine={page === 'tasks'} /> : null}
      {page === 'overview' ? <Overview state={state} navigate={navigate} onLead={openLead} onTask={taskProps.onOpen} /> : null}
      {page === 'clients' ? <Clients state={state} search={search} onLead={openLead} onCreate={() => setModal({ type: 'lead-new' })} /> : null}
      {page === 'communications' ? <Communications state={state} search={search} onCreate={(siteId) => setModal({ type: 'activity', siteId })} onLead={openLead} /> : null}
      {page === 'calendar' ? <Calendar state={state} search={search} onLead={openLead} onTask={taskProps.onOpen} /> : null}
    </main></div>{dialog}{toast ? <div className={`toast ${toast.error ? 'error' : ''}`} role={toast.error ? 'alert' : 'status'}>{toast.error ? <AlertCircle size={19} /> : <CircleCheck size={19} />}<span>{toast.text}</span><button className="icon-button" onClick={() => setToast(null)} aria-label="Закрыть уведомление"><X size={15} /></button></div> : null}
  </div>;
}
