import { useState } from 'react';
import { Download, Upload, RotateCcw } from 'lucide-react';
import { Field } from './UI.jsx';
import { ACTIVITY_TYPES, LEAD_STAGES, TASK_STAGES, createDemoState, dueAt, STORAGE_KEY, validateState } from '../app/model.js';

function Form({ children, onSubmit, onClose, label = 'Сохранить' }) {
  const [error, setError] = useState('');
  return <form onSubmit={(event) => { event.preventDefault(); setError(''); try { onSubmit(Object.fromEntries(new FormData(event.currentTarget))); } catch (e) { setError(e.message); } }}><div className="form-content">{children}{error ? <p className="form-error" role="alert">{error}</p> : null}</div><footer className="dialog-actions"><button type="button" className="button" onClick={onClose}>Отмена</button><button className="button primary" type="submit">{label}</button></footer></form>;
}
export function PersonSelect({ state, name = 'ownerId', value, workers = false, allowEmpty = false }) { return <select name={name} defaultValue={value || ''}>{allowEmpty ? <option value="">Не назначен</option> : null}{state.employees.filter((p) => p.active && (workers ? p.role === 'Цех' : p.role !== 'Цех')).map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</select>; }
export function LeadForm({ state, lead, onSubmit, onClose }) {
  const [clientId, setClientId] = useState('');
  return <Form onSubmit={onSubmit} onClose={onClose} label={lead ? 'Сохранить изменения' : 'Создать заявку'}><div className="form-grid">
    {!lead ? <><Field label="Клиент" wide><select name="clientId" value={clientId} onChange={(e) => setClientId(e.target.value)}><option value="">Новый клиент</option>{state.clients.map((c) => <option value={c.id} key={c.id}>{c.name}</option>)}</select></Field>{!clientId ? <><Field label="Имя / название *" wide><input name="name" required maxLength={200} placeholder="Например, Александр Иванов" autoFocus /></Field><Field label="Телефон"><input name="phone" type="tel" maxLength={60} /></Field><Field label="Почта"><input name="email" type="email" maxLength={200} /></Field></> : null}<Field label="Объект *"><input name="siteName" placeholder="Дом 8 × 10" required maxLength={200} /></Field><Field label="Адрес"><input name="address" maxLength={500} /></Field><Field label="Источник"><select name="source"><option>Сайт</option><option>Телефон</option><option>Рекомендация</option><option>Мессенджер</option><option>Вручную</option></select></Field></> : <Field label="Этап"><select name="status" defaultValue={lead.status}>{LEAD_STAGES.map((v) => <option key={v.id} value={v.id}>{v.label}</option>)}</select></Field>}
    <Field label="Ответственный"><PersonSelect state={state} value={lead?.ownerId || 'manager-1'} /></Field><Field label="Следующий шаг *" wide><input name="nextAction" required maxLength={500} defaultValue={lead?.nextAction || ''} placeholder="Позвонить и уточнить комплектацию" /></Field><Field label="Срок контакта" wide><input name="dueAt" type="datetime-local" defaultValue={lead?.dueAt || dueAt(1, '12:00')} /></Field><Field label="Примечание" wide><textarea name="notes" rows={3} maxLength={5000} defaultValue={lead?.notes || ''} /></Field>
  </div></Form>;
}
export function ClientForm({ client, site, onSubmit, onClose }) { return <Form onSubmit={onSubmit} onClose={onClose}><div className="form-grid"><Field label="Клиент *" wide><input name="name" required defaultValue={client.name} maxLength={200} autoFocus /></Field><Field label="Телефон"><input name="phone" type="tel" defaultValue={client.phone} maxLength={60} /></Field><Field label="Почта"><input name="email" type="email" defaultValue={client.email} maxLength={200} /></Field><Field label="Объект *" wide><input name="siteName" required defaultValue={site.name} maxLength={200} /></Field><Field label="Адрес" wide><input name="address" defaultValue={site.address} maxLength={500} /></Field></div></Form>; }
export function ActivityForm({ state, siteId, onSubmit, onClose }) { return <Form onSubmit={onSubmit} onClose={onClose} label="Добавить в историю"><div className="form-grid"><Field label="Объект" wide><select name="siteId" defaultValue={siteId || state.sites[0]?.id} required>{state.sites.map((s) => <option key={s.id} value={s.id}>{state.clients.find((c) => c.id === s.clientId)?.name} · {s.name}</option>)}</select></Field><Field label="Вид общения" wide><select name="type" defaultValue="call">{Object.entries(ACTIVITY_TYPES).filter(([id]) => id !== 'system').map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></Field><Field label="Результат общения *" wide><textarea name="text" required rows={5} maxLength={5000} autoFocus placeholder="О чём договорились и что делать дальше" /></Field><p className="form-hint field-wide">Запись появится в истории объекта. Подключение почты и мессенджеров запланировано следующим этапом.</p></div></Form>; }
export function OrderForm({ state, onSubmit, onClose }) { return <Form onSubmit={(p) => onSubmit({ ...p, approved: p.approved === 'on' })} onClose={onClose} label="Передать в цех"><div className="form-grid"><Field label="Согласованная комплектация *" wide><textarea name="scope" required rows={5} maxLength={5000} autoFocus placeholder="Состав комплекта, толщина панелей, объём и требования к изготовлению" /></Field><Field label="Номер или ссылка на спецификацию" wide><input name="reference" maxLength={1000} placeholder="КП-0042, версия 2" /></Field><Field label="Исполнитель первого задания"><PersonSelect state={state} name="assigneeId" workers allowEmpty /></Field><Field label="Срок подготовки"><input name="dueAt" type="datetime-local" defaultValue={dueAt(1)} /></Field><label className="check-row field-wide"><input type="checkbox" name="approved" required />Комплектация согласована с клиентом</label><p className="form-hint field-wide">Будет создан заказ с сохранённой комплектацией и первое задание «Подготовить заказ к производству».</p></div></Form>; }
export function TaskForm({ state, task, orderId, onSubmit, onClose }) {
  const [status, setStatus] = useState(task?.status || 'planned');
  return <Form onSubmit={onSubmit} onClose={onClose} label={task ? 'Сохранить задание' : 'Создать задание'}><div className="form-grid"><Field label="Название задания *" wide><input name="title" required defaultValue={task?.title || ''} maxLength={200} autoFocus placeholder="Например, раскрой панелей пола" /></Field><Field label="Заказ *" wide><select name="orderId" defaultValue={task?.orderId || orderId || state.orders[0]?.id} required>{state.orders.map((o) => <option key={o.id} value={o.id}>{o.number} · {state.sites.find((s) => s.id === o.siteId)?.name}</option>)}</select></Field><Field label="Исполнитель"><PersonSelect state={state} name="assigneeId" value={task?.assigneeId || ''} workers allowEmpty /></Field><Field label="Срок"><input name="dueAt" type="datetime-local" defaultValue={task?.dueAt || dueAt(0)} /></Field><Field label="Статус"><select name="status" value={status} onChange={(e) => setStatus(e.target.value)}>{TASK_STAGES.map((v) => <option key={v.id} value={v.id}>{v.label}</option>)}</select></Field><Field label="Приоритет"><select name="priority" defaultValue={task?.priority || 'normal'}><option value="normal">Обычный</option><option value="high">Высокий</option></select></Field>{status === 'blocked' ? <Field label="Причина блокировки *" wide><input name="blockReason" required maxLength={500} defaultValue={task?.blockReason || ''} /></Field> : null}<Field label="Общий объём *"><input name="quantity" type="number" min="0.01" max="1000000" step="0.01" required defaultValue={task?.quantity || 1} /></Field><Field label="Готовый объём"><input name="completedQty" type="number" min="0" max="1000000" step="0.01" defaultValue={task?.completedQty || 0} required /></Field><Field label="Единица *"><input name="unit" required maxLength={40} defaultValue={task?.unit || 'комплект'} /></Field><Field label="Описание результата" wide><textarea name="description" rows={3} maxLength={5000} defaultValue={task?.description || ''} /></Field></div></Form>;
}
export function DataTools({ state, replace, onClose }) {
  const [pending, setPending] = useState(null); const [error, setError] = useState('');
  function exportData() { const raw = localStorage.getItem(STORAGE_KEY) || JSON.stringify(state, null, 2); const url = URL.createObjectURL(new Blob([raw], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = `eft-crm-${new Date().toISOString().slice(0, 10)}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  async function importData(event) { setError(''); const file = event.target.files[0]; if (!file) return; try { if (file.size > 4 * 1024 * 1024) throw new Error('Файл должен быть меньше 4 МБ'); setPending({ data: validateState(JSON.parse(await file.text())), title: 'Заменить данные в этом браузере содержимым файла?' }); } catch (e) { setError(`Импорт не выполнен: ${e.message}`); } event.target.value = ''; }
  return <div className="form-content"><p className="data-explanation">Это ознакомительная версия. Записи сохраняются в этом браузере и доступны только на этом устройстве. Общая база и вход сотрудников появятся на следующем этапе.</p><div className="data-actions"><button className="button" onClick={exportData}><Download size={17} />Экспортировать данные</button><label className="button file-button"><Upload size={17} />Восстановить из файла<input type="file" accept="application/json,.json" onChange={importData} /></label><button className="button" onClick={() => setPending({ data: createDemoState(), title: 'Заменить текущие записи демонстрационными примерами?' })}><RotateCcw size={17} />Вернуть демо-примеры</button></div>{pending ? <div className="confirmation"><strong>{pending.title}</strong><p>Сначала экспортируйте текущие записи, если хотите их сохранить.</p><div><button className="button" onClick={() => setPending(null)}>Отмена</button><button className="button primary" onClick={() => { try { replace(pending.data); onClose(); } catch (e) { setError(e.message); } }}>Заменить данные</button></div></div> : null}{error ? <p className="form-error" role="alert">{error}</p> : null}<a className="text-link" href="?view=design">Посмотреть согласованные макеты</a></div>;
}
